
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountSecurityLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.AchievementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  description: 'description',
  icon: 'icon',
  imageUrl: 'imageUrl',
  color: 'color',
  category: 'category',
  rarity: 'rarity',
  conditionKey: 'conditionKey',
  conditionValue: 'conditionValue',
  isAutoGrant: 'isAutoGrant',
  isVisible: 'isVisible',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  coverUrl: 'coverUrl',
  pointsReward: 'pointsReward',
  signupLimit: 'signupLimit',
  signupCount: 'signupCount',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  activityId: 'activityId',
  userId: 'userId'
};

exports.Prisma.ActivityRegistrationScalarFieldEnum = {
  id: 'id',
  note: 'note',
  checkedInAt: 'checkedInAt',
  createdAt: 'createdAt',
  activityId: 'activityId',
  userId: 'userId'
};

exports.Prisma.AdminActionScalarFieldEnum = {
  id: 'id',
  action: 'action',
  reason: 'reason',
  metadata: 'metadata',
  createdAt: 'createdAt',
  adminId: 'adminId',
  targetUserId: 'targetUserId',
  postId: 'postId',
  replyId: 'replyId',
  boardId: 'boardId'
};

exports.Prisma.AdminActionLogScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  action: 'action',
  targetUserId: 'targetUserId',
  detail: 'detail',
  createdAt: 'createdAt'
};

exports.Prisma.AdminPermissionScalarFieldEnum = {
  id: 'id',
  permissionKey: 'permissionKey',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  isPinned: 'isPinned',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BadgeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  iconUrl: 'iconUrl',
  pointsCost: 'pointsCost',
  isAutoGrant: 'isAutoGrant',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  link: 'link',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BlockScalarFieldEnum = {
  id: 'id',
  reason: 'reason',
  createdAt: 'createdAt',
  blockerId: 'blockerId',
  blockedId: 'blockedId'
};

exports.Prisma.BoardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  sortOrder: 'sortOrder',
  postCount: 'postCount',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  categoryId: 'categoryId',
  coverUrl: 'coverUrl',
  followerCount: 'followerCount',
  isHot: 'isHot',
  isRecommended: 'isRecommended',
  parentId: 'parentId'
};

exports.Prisma.BoardCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BoardFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  boardId: 'boardId',
  userId: 'userId'
};

exports.Prisma.ChangelogScalarFieldEnum = {
  id: 'id',
  version: 'version',
  major: 'major',
  minor: 'minor',
  patch: 'patch',
  title: 'title',
  content: 'content',
  type: 'type',
  isMajor: 'isMajor',
  status: 'status',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdById: 'createdById'
};

exports.Prisma.CheckInScalarFieldEnum = {
  id: 'id',
  checkDate: 'checkDate',
  points: 'points',
  streakDay: 'streakDay',
  createdAt: 'createdAt',
  userId: 'userId',
  isMakeUp: 'isMakeUp',
  exp: 'exp',
  message: 'message',
  mood: 'mood',
  checkinDateKey: 'checkinDateKey'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastMessageAt: 'lastMessageAt',
  pairKey: 'pairKey'
};

exports.Prisma.ConversationParticipantScalarFieldEnum = {
  id: 'id',
  lastReadAt: 'lastReadAt',
  isDeleted: 'isDeleted',
  isMuted: 'isMuted',
  joinedAt: 'joinedAt',
  conversationId: 'conversationId',
  userId: 'userId'
};

exports.Prisma.CultureCommentScalarFieldEnum = {
  id: 'id',
  content: 'content',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  itemId: 'itemId',
  userId: 'userId'
};

exports.Prisma.CultureFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  itemId: 'itemId',
  userId: 'userId'
};

exports.Prisma.CultureItemScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  slug: 'slug',
  subtitle: 'subtitle',
  coverUrl: 'coverUrl',
  releaseDate: 'releaseDate',
  lyricist: 'lyricist',
  composer: 'composer',
  arranger: 'arranger',
  albumName: 'albumName',
  roleName: 'roleName',
  city: 'city',
  summary: 'summary',
  background: 'background',
  legalExcerpt: 'legalExcerpt',
  mvUrl: 'mvUrl',
  liveUrl: 'liveUrl',
  trailerUrl: 'trailerUrl',
  rating: 'rating',
  favoriteCount: 'favoriteCount',
  commentCount: 'commentCount',
  isVisible: 'isVisible',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DailyExperienceRecordScalarFieldEnum = {
  id: 'id',
  date: 'date',
  amount: 'amount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.DailyMessageScalarFieldEnum = {
  id: 'id',
  date: 'date',
  mood: 'mood',
  content: 'content',
  likeCount: 'likeCount',
  commentCount: 'commentCount',
  favoriteCount: 'favoriteCount',
  shareCount: 'shareCount',
  isPinned: 'isPinned',
  isFeatured: 'isFeatured',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  checkInId: 'checkInId'
};

exports.Prisma.DailyMessageCommentScalarFieldEnum = {
  id: 'id',
  content: 'content',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  messageId: 'messageId',
  authorId: 'authorId',
  parentId: 'parentId'
};

exports.Prisma.DailyMessageFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  messageId: 'messageId',
  userId: 'userId'
};

exports.Prisma.DailyMessageLikeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  messageId: 'messageId',
  userId: 'userId'
};

exports.Prisma.DailyQuoteScalarFieldEnum = {
  id: 'id',
  content: 'content',
  source: 'source',
  songTitle: 'songTitle',
  isPinned: 'isPinned',
  isVisible: 'isVisible',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DailyTaskProgressScalarFieldEnum = {
  id: 'id',
  taskDate: 'taskDate',
  progress: 'progress',
  isCompleted: 'isCompleted',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  templateId: 'templateId'
};

exports.Prisma.DailyTaskTemplateScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  target: 'target',
  points: 'points',
  exp: 'exp',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DirectMessageScalarFieldEnum = {
  id: 'id',
  type: 'type',
  content: 'content',
  imageUrl: 'imageUrl',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  conversationId: 'conversationId',
  senderId: 'senderId'
};

exports.Prisma.EmailVerificationScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  email: 'email',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.EntertainmentDailyDrawScalarFieldEnum = {
  id: 'id',
  dateKey: 'dateKey',
  points: 'points',
  prescriptionCode: 'prescriptionCode',
  lyricText: 'lyricText',
  songTitle: 'songTitle',
  albumTitle: 'albumTitle',
  createdAt: 'createdAt',
  userId: 'userId',
  lyricPrescriptionId: 'lyricPrescriptionId'
};

exports.Prisma.ExperienceLogScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  type: 'type',
  description: 'description',
  createdAt: 'createdAt',
  userId: 'userId',
  sourceType: 'sourceType',
  sourceId: 'sourceId'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  content: 'content',
  imageUrl: 'imageUrl',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  contact: 'contact',
  adminUnread: 'adminUnread',
  userUnread: 'userUnread',
  lastReplyAt: 'lastReplyAt',
  lastUserReplyAt: 'lastUserReplyAt',
  lastAdminReplyAt: 'lastAdminReplyAt',
  closedAt: 'closedAt',
  idempotencyKeyHash: 'idempotencyKeyHash'
};

exports.Prisma.FeedbackAttachmentScalarFieldEnum = {
  id: 'id',
  url: 'url',
  mimeType: 'mimeType',
  createdAt: 'createdAt',
  feedbackId: 'feedbackId',
  replyId: 'replyId'
};

exports.Prisma.FeedbackReplyScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  feedbackId: 'feedbackId',
  adminId: 'adminId',
  authorRole: 'authorRole',
  isReadByUser: 'isReadByUser',
  isReadByAdmin: 'isReadByAdmin'
};

exports.Prisma.FollowScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  followerId: 'followerId',
  followingId: 'followingId'
};

exports.Prisma.FriendActivityScalarFieldEnum = {
  id: 'id',
  mood: 'mood',
  content: 'content',
  createdAt: 'createdAt',
  actorId: 'actorId',
  checkInId: 'checkInId',
  dailyMessageId: 'dailyMessageId',
  type: 'type',
  targetUrl: 'targetUrl'
};

exports.Prisma.FriendRequestScalarFieldEnum = {
  id: 'id',
  message: 'message',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  senderId: 'senderId',
  receiverId: 'receiverId'
};

exports.Prisma.FriendshipScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userAId: 'userAId',
  userBId: 'userBId'
};

exports.Prisma.GrowthLevelConfigScalarFieldEnum = {
  id: 'id',
  level: 'level',
  name: 'name',
  requiredExp: 'requiredExp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GuessSongAudioVariantScalarFieldEnum = {
  id: 'id',
  durationSeconds: 'durationSeconds',
  storagePath: 'storagePath',
  fileSize: 'fileSize',
  createdAt: 'createdAt',
  questionId: 'questionId'
};

exports.Prisma.GuessSongLeaderboardEntryScalarFieldEnum = {
  id: 'id',
  mode: 'mode',
  periodType: 'periodType',
  periodKey: 'periodKey',
  score: 'score',
  correctCount: 'correctCount',
  maxStreak: 'maxStreak',
  totalPlayCount: 'totalPlayCount',
  achievedAt: 'achievedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  sessionId: 'sessionId'
};

exports.Prisma.GuessSongPlayRequestScalarFieldEnum = {
  id: 'id',
  requestKey: 'requestKey',
  playCountAfter: 'playCountAfter',
  createdAt: 'createdAt',
  sessionQuestionId: 'sessionQuestionId',
  audioVariantId: 'audioVariantId'
};

exports.Prisma.GuessSongQuestionScalarFieldEnum = {
  id: 'id',
  songTitle: 'songTitle',
  albumTitle: 'albumTitle',
  difficulty: 'difficulty',
  enabled: 'enabled',
  allowEndless: 'allowEndless',
  correctAnswer: 'correctAnswer',
  wrongOption1: 'wrongOption1',
  wrongOption2: 'wrongOption2',
  wrongOption3: 'wrongOption3',
  sourceAudioPath: 'sourceAudioPath',
  audioDurationMs: 'audioDurationMs',
  processingStatus: 'processingStatus',
  processingError: 'processingError',
  playCount: 'playCount',
  answerCount: 'answerCount',
  correctCount: 'correctCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  musicSongId: 'musicSongId'
};

exports.Prisma.GuessSongSessionScalarFieldEnum = {
  id: 'id',
  activeKey: 'activeKey',
  mode: 'mode',
  status: 'status',
  score: 'score',
  correctCount: 'correctCount',
  wrongCount: 'wrongCount',
  currentStreak: 'currentStreak',
  maxStreak: 'maxStreak',
  livesRemaining: 'livesRemaining',
  totalPlayCount: 'totalPlayCount',
  currentPosition: 'currentPosition',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.GuessSongSessionQuestionScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  position: 'position',
  playbackDurationSeconds: 'playbackDurationSeconds',
  maxPlayCount: 'maxPlayCount',
  playCount: 'playCount',
  optionsSnapshot: 'optionsSnapshot',
  correctOptionKey: 'correctOptionKey',
  selectedOptionKey: 'selectedOptionKey',
  isCorrect: 'isCorrect',
  awardedScore: 'awardedScore',
  answerDeadlineAt: 'answerDeadlineAt',
  answeredAt: 'answeredAt',
  createdAt: 'createdAt',
  sessionId: 'sessionId',
  questionId: 'questionId'
};

exports.Prisma.LikeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  postId: 'postId',
  userId: 'userId'
};

exports.Prisma.LoginDeviceScalarFieldEnum = {
  id: 'id',
  deviceType: 'deviceType',
  deviceName: 'deviceName',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.LotteryScalarFieldEnum = {
  id: 'id',
  title: 'title',
  pointsCost: 'pointsCost',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  createdAt: 'createdAt',
  activityId: 'activityId'
};

exports.Prisma.LotteryEntryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  lotteryId: 'lotteryId',
  prizeId: 'prizeId',
  userId: 'userId'
};

exports.Prisma.LotteryPrizeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  quantity: 'quantity',
  remaining: 'remaining',
  pointsValue: 'pointsValue',
  metadata: 'metadata',
  lotteryId: 'lotteryId'
};

exports.Prisma.LyricCardScalarFieldEnum = {
  id: 'id',
  lyric: 'lyric',
  imageUrl: 'imageUrl',
  isFavorite: 'isFavorite',
  createdAt: 'createdAt',
  userId: 'userId',
  songId: 'songId',
  templateId: 'templateId'
};

exports.Prisma.LyricCardTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  backgroundUrl: 'backgroundUrl',
  textColor: 'textColor',
  accentColor: 'accentColor',
  isVisible: 'isVisible',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LyricPrescriptionScalarFieldEnum = {
  id: 'id',
  text: 'text',
  songTitle: 'songTitle',
  albumTitle: 'albumTitle',
  enabled: 'enabled',
  displayCount: 'displayCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MusicAlbumScalarFieldEnum = {
  id: 'id',
  name: 'name',
  artist: 'artist',
  releaseYear: 'releaseYear',
  coverUrl: 'coverUrl',
  description: 'description',
  language: 'language',
  createdAt: 'createdAt',
  era: 'era',
  albumType: 'albumType',
  releaseDate: 'releaseDate',
  company: 'company',
  story: 'story',
  status: 'status',
  displayOrder: 'displayOrder'
};

exports.Prisma.MusicFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  trackId: 'trackId',
  userId: 'userId'
};

exports.Prisma.MusicPlayRecordScalarFieldEnum = {
  id: 'id',
  durationSeconds: 'durationSeconds',
  playedAt: 'playedAt',
  trackId: 'trackId',
  userId: 'userId'
};

exports.Prisma.MusicSongScalarFieldEnum = {
  id: 'id',
  title: 'title',
  artist: 'artist',
  albumId: 'albumId',
  trackNumber: 'trackNumber',
  releaseYear: 'releaseYear',
  duration: 'duration',
  coverUrl: 'coverUrl',
  composer: 'composer',
  lyricist: 'lyricist',
  arranger: 'arranger',
  producer: 'producer',
  story: 'story',
  lyrics: 'lyrics',
  sourceType: 'sourceType',
  sourceUrl: 'sourceUrl',
  createdAt: 'createdAt',
  language: 'language',
  tags: 'tags',
  era: 'era',
  trackType: 'trackType',
  concertVersion: 'concertVersion',
  mood: 'mood',
  scene: 'scene',
  recommendLevel: 'recommendLevel',
  description: 'description'
};

exports.Prisma.MusicTrackScalarFieldEnum = {
  id: 'id',
  title: 'title',
  artist: 'artist',
  source: 'source',
  sourceUrl: 'sourceUrl',
  isPlayable: 'isPlayable',
  sortOrder: 'sortOrder',
  isVisible: 'isVisible',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  content: 'content',
  link: 'link',
  isRead: 'isRead',
  createdAt: 'createdAt',
  readAt: 'readAt',
  recipientId: 'recipientId',
  actorId: 'actorId',
  key: 'key',
  completedAt: 'completedAt'
};

exports.Prisma.OnlineSessionScalarFieldEnum = {
  id: 'id',
  tokenId: 'tokenId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.PageLayoutScalarFieldEnum = {
  id: 'id',
  pageKey: 'pageKey',
  draftConfig: 'draftConfig',
  publishedConfig: 'publishedConfig',
  previousPublishedConfig: 'previousPublishedConfig',
  version: 'version',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  updatedById: 'updatedById',
  publishedById: 'publishedById'
};

exports.Prisma.PageLayoutRevisionScalarFieldEnum = {
  id: 'id',
  pageLayoutId: 'pageLayoutId',
  version: 'version',
  config: 'config',
  note: 'note',
  source: 'source',
  createdAt: 'createdAt',
  publishedById: 'publishedById'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  consumedAt: 'consumedAt',
  createdAt: 'createdAt',
  userId: 'userId',
  type: 'type',
  stage: 'stage',
  codeHash: 'codeHash',
  attemptCount: 'attemptCount'
};

exports.Prisma.PointLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  points: 'points',
  before: 'before',
  after: 'after',
  reason: 'reason',
  createdAt: 'createdAt',
  userId: 'userId',
  postId: 'postId',
  replyId: 'replyId',
  checkInId: 'checkInId',
  activityId: 'activityId',
  badgeId: 'badgeId',
  dailyDrawId: 'dailyDrawId',
  dateKey: 'dateKey',
  businessKey: 'businessKey'
};

exports.Prisma.PollScalarFieldEnum = {
  id: 'id',
  question: 'question',
  allowMulti: 'allowMulti',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  postId: 'postId'
};

exports.Prisma.PollOptionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  voteCount: 'voteCount',
  sortOrder: 'sortOrder',
  pollId: 'pollId'
};

exports.Prisma.PollVoteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  pollId: 'pollId',
  optionId: 'optionId',
  userId: 'userId'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  viewCount: 'viewCount',
  likeCount: 'likeCount',
  replyCount: 'replyCount',
  isPinned: 'isPinned',
  isFeatured: 'isFeatured',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  authorId: 'authorId',
  boardId: 'boardId',
  contentType: 'contentType',
  favoriteCount: 'favoriteCount',
  isLocked: 'isLocked',
  isRecommended: 'isRecommended',
  publishedAt: 'publishedAt',
  readUserCount: 'readUserCount',
  shareCount: 'shareCount',
  status: 'status',
  summary: 'summary'
};

exports.Prisma.PostFavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  postId: 'postId',
  userId: 'userId'
};

exports.Prisma.PostMediaScalarFieldEnum = {
  id: 'id',
  type: 'type',
  url: 'url',
  thumbnail: 'thumbnail',
  width: 'width',
  height: 'height',
  size: 'size',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  postId: 'postId'
};

exports.Prisma.PostTagScalarFieldEnum = {
  postId: 'postId',
  tagId: 'tagId'
};

exports.Prisma.ProfileScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  avatarUrl: 'avatarUrl',
  backgroundUrl: 'backgroundUrl',
  bio: 'bio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  wallVisibility: 'wallVisibility'
};

exports.Prisma.ProfileWallLikeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  messageId: 'messageId',
  userId: 'userId'
};

exports.Prisma.ProfileWallMessageScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  senderId: 'senderId',
  receiverId: 'receiverId',
  parentId: 'parentId',
  likeCount: 'likeCount'
};

exports.Prisma.RateLimitLogScalarFieldEnum = {
  id: 'id',
  key: 'key',
  action: 'action',
  count: 'count',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.ReplyScalarFieldEnum = {
  id: 'id',
  content: 'content',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  postId: 'postId',
  authorId: 'authorId',
  parentId: 'parentId',
  likeCount: 'likeCount'
};

exports.Prisma.ReplyLikeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  replyId: 'replyId',
  userId: 'userId'
};

exports.Prisma.ReportScalarFieldEnum = {
  id: 'id',
  targetType: 'targetType',
  reason: 'reason',
  description: 'description',
  status: 'status',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt',
  reporterId: 'reporterId',
  targetUserId: 'targetUserId',
  postId: 'postId',
  replyId: 'replyId',
  dailyMessageId: 'dailyMessageId'
};

exports.Prisma.SearchHistoryScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.SearchKeywordScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  count: 'count',
  lastUsedAt: 'lastUsedAt'
};

exports.Prisma.SensitiveWordScalarFieldEnum = {
  id: 'id',
  word: 'word',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.SiteSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  valueType: 'valueType',
  group: 'group',
  label: 'label',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SmsCodeScalarFieldEnum = {
  id: 'id',
  phone: 'phone',
  codeHash: 'codeHash',
  scene: 'scene',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SystemNotificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  link: 'link',
  type: 'type',
  isPublished: 'isPublished',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdById: 'createdById',
  cover: 'cover',
  priority: 'priority',
  popup: 'popup',
  sticky: 'sticky',
  publishAt: 'publishAt',
  expireAt: 'expireAt',
  published: 'published',
  buttonText: 'buttonText',
  buttonUrl: 'buttonUrl',
  version: 'version'
};

exports.Prisma.SystemNotificationReadScalarFieldEnum = {
  id: 'id',
  readAt: 'readAt',
  notificationId: 'notificationId',
  userId: 'userId'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  usageCount: 'usageCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  expReward: 'expReward',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  phone: 'phone',
  passwordHash: 'passwordHash',
  nickname: 'nickname',
  avatarUrl: 'avatarUrl',
  bio: 'bio',
  role: 'role',
  level: 'level',
  points: 'points',
  consecutiveDays: 'consecutiveDays',
  lastCheckInDate: 'lastCheckInDate',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  backgroundUrl: 'backgroundUrl',
  emailVerifiedAt: 'emailVerifiedAt',
  exp: 'exp',
  isOnline: 'isOnline',
  lastActiveAt: 'lastActiveAt',
  lastLoginAt: 'lastLoginAt',
  phoneVerifiedAt: 'phoneVerifiedAt',
  status: 'status',
  verificationStatus: 'verificationStatus',
  nicknameChangedAt: 'nicknameChangedAt',
  uid: 'uid',
  experience: 'experience',
  securityQuestionRecoveryEnabled: 'securityQuestionRecoveryEnabled',
  registrationIdempotencyKeyHash: 'registrationIdempotencyKeyHash',
  mustSetupSecurity: 'mustSetupSecurity',
  usernameNormalized: 'usernameNormalized',
  checkinMoodEnabled: 'checkinMoodEnabled'
};

exports.Prisma.UserAchievementScalarFieldEnum = {
  id: 'id',
  progress: 'progress',
  unlocked: 'unlocked',
  unlockedAt: 'unlockedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  achievementId: 'achievementId'
};

exports.Prisma.UserAlbumCollectionScalarFieldEnum = {
  id: 'id',
  owned: 'owned',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  albumId: 'albumId'
};

exports.Prisma.UserBadgeScalarFieldEnum = {
  id: 'id',
  isHidden: 'isHidden',
  displayOrder: 'displayOrder',
  grantedAt: 'grantedAt',
  userId: 'userId',
  badgeId: 'badgeId'
};

exports.Prisma.UserSecurityQuestionScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answerHash: 'answerHash',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.AchievementCategory = exports.$Enums.AchievementCategory = {
  REGISTER: 'REGISTER',
  CHECKIN_STREAK: 'CHECKIN_STREAK',
  CHECKIN_TOTAL: 'CHECKIN_TOTAL',
  POST: 'POST',
  MUSIC: 'MUSIC',
  FRIEND: 'FRIEND',
  ACTIVE: 'ACTIVE',
  SPECIAL: 'SPECIAL'
};

exports.AchievementRarity = exports.$Enums.AchievementRarity = {
  NORMAL: 'NORMAL',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
  LIMITED: 'LIMITED'
};

exports.ActivityType = exports.$Enums.ActivityType = {
  CONCERT_SIGNUP: 'CONCERT_SIGNUP',
  GATHERING: 'GATHERING',
  ONLINE: 'ONLINE',
  LOTTERY: 'LOTTERY',
  OTHER: 'OTHER'
};

exports.ActivityStatus = exports.$Enums.ActivityStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED'
};

exports.AdminActionType = exports.$Enums.AdminActionType = {
  DELETE_POST: 'DELETE_POST',
  RESTORE_POST: 'RESTORE_POST',
  PIN_POST: 'PIN_POST',
  UNPIN_POST: 'UNPIN_POST',
  FEATURE_POST: 'FEATURE_POST',
  UNFEATURE_POST: 'UNFEATURE_POST',
  DELETE_REPLY: 'DELETE_REPLY',
  RESTORE_REPLY: 'RESTORE_REPLY',
  ADJUST_POINTS: 'ADJUST_POINTS',
  UPDATE_BOARD: 'UPDATE_BOARD',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  DELETE_USER: 'DELETE_USER',
  RESTORE_USER: 'RESTORE_USER',
  BAN_USER: 'BAN_USER',
  UNBAN_USER: 'UNBAN_USER',
  UPDATE_USER_POINTS: 'UPDATE_USER_POINTS',
  RECOMMEND_POST: 'RECOMMEND_POST',
  UNRECOMMEND_POST: 'UNRECOMMEND_POST',
  LOCK_POST: 'LOCK_POST',
  UNLOCK_POST: 'UNLOCK_POST',
  CREATE_BOARD: 'CREATE_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',
  CREATE_BADGE: 'CREATE_BADGE',
  GRANT_BADGE: 'GRANT_BADGE',
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  UPDATE_SETTING: 'UPDATE_SETTING'
};

exports.ChangelogType = exports.$Enums.ChangelogType = {
  FEATURE: 'FEATURE',
  IMPROVEMENT: 'IMPROVEMENT',
  FIX: 'FIX',
  SECURITY: 'SECURITY',
  CONTENT: 'CONTENT'
};

exports.ChangelogStatus = exports.$Enums.ChangelogStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  UNPUBLISHED: 'UNPUBLISHED'
};

exports.CultureContentType = exports.$Enums.CultureContentType = {
  SONG: 'SONG',
  ALBUM: 'ALBUM',
  FILM: 'FILM',
  LIVE: 'LIVE'
};

exports.MessageType = exports.$Enums.MessageType = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  EMOJI: 'EMOJI',
  SYSTEM: 'SYSTEM'
};

exports.ExperienceLogType = exports.$Enums.ExperienceLogType = {
  CHECKIN: 'CHECKIN',
  TASK: 'TASK',
  POST: 'POST',
  COMMENT: 'COMMENT',
  LIKE: 'LIKE',
  ACTIVITY: 'ACTIVITY',
  ADMIN: 'ADMIN',
  OTHER: 'OTHER'
};

exports.FeedbackType = exports.$Enums.FeedbackType = {
  BUG: 'BUG',
  SUGGESTION: 'SUGGESTION',
  CONTENT: 'CONTENT',
  ACCOUNT: 'ACCOUNT',
  OTHER: 'OTHER',
  EXPERIENCE: 'EXPERIENCE'
};

exports.FeedbackStatus = exports.$Enums.FeedbackStatus = {
  OPEN: 'OPEN',
  REPLIED: 'REPLIED',
  CLOSED: 'CLOSED',
  PROCESSING: 'PROCESSING',
  RESOLVED: 'RESOLVED'
};

exports.FriendRequestStatus = exports.$Enums.FriendRequestStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

exports.GuessSongMode = exports.$Enums.GuessSongMode = {
  EASY: 'EASY',
  ADVANCED: 'ADVANCED',
  HARD: 'HARD',
  ENDLESS: 'ENDLESS'
};

exports.GuessSongPeriodType = exports.$Enums.GuessSongPeriodType = {
  WEEK: 'WEEK',
  MONTH: 'MONTH'
};

exports.GuessSongDifficulty = exports.$Enums.GuessSongDifficulty = {
  EASY: 'EASY',
  ADVANCED: 'ADVANCED',
  HARD: 'HARD'
};

exports.GuessSongProcessingStatus = exports.$Enums.GuessSongProcessingStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED'
};

exports.GuessSongSessionStatus = exports.$Enums.GuessSongSessionStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
  EXPIRED: 'EXPIRED'
};

exports.DeviceType = exports.$Enums.DeviceType = {
  WEB: 'WEB',
  MOBILE: 'MOBILE',
  TABLET: 'TABLET',
  API: 'API'
};

exports.RewardType = exports.$Enums.RewardType = {
  BADGE: 'BADGE',
  PHYSICAL: 'PHYSICAL',
  COUPON: 'COUPON',
  POINTS: 'POINTS'
};

exports.MusicPublicationStatus = exports.$Enums.MusicPublicationStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  REPLY: 'REPLY',
  LIKE: 'LIKE',
  SYSTEM: 'SYSTEM',
  MESSAGE: 'MESSAGE',
  ACTIVITY: 'ACTIVITY',
  ADMIN: 'ADMIN',
  FOLLOW: 'FOLLOW',
  BADGE: 'BADGE',
  FRIEND_REQUEST: 'FRIEND_REQUEST'
};

exports.PageLayoutRevisionSource = exports.$Enums.PageLayoutRevisionSource = {
  MANUAL: 'MANUAL',
  ROLLBACK: 'ROLLBACK',
  DEFAULT: 'DEFAULT'
};

exports.PasswordResetType = exports.$Enums.PasswordResetType = {
  SECURITY_QUESTION: 'SECURITY_QUESTION',
  EMAIL: 'EMAIL'
};

exports.PasswordResetStage = exports.$Enums.PasswordResetStage = {
  CHALLENGE: 'CHALLENGE',
  RESET_CODE: 'RESET_CODE',
  RESET_TOKEN: 'RESET_TOKEN'
};

exports.PointActionType = exports.$Enums.PointActionType = {
  POST_CREATE: 'POST_CREATE',
  REPLY_CREATE: 'REPLY_CREATE',
  DAILY_CHECK_IN: 'DAILY_CHECK_IN',
  POST_LIKE_RECEIVED: 'POST_LIKE_RECEIVED',
  ADMIN_ADJUST: 'ADMIN_ADJUST',
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  CONTINUOUS_CHECK_IN_BONUS: 'CONTINUOUS_CHECK_IN_BONUS',
  FEATURED_POST: 'FEATURED_POST',
  ACTIVITY_REWARD: 'ACTIVITY_REWARD',
  BADGE_EXCHANGE: 'BADGE_EXCHANGE',
  ENTERTAINMENT_DAILY_DRAW: 'ENTERTAINMENT_DAILY_DRAW',
  POST_DAILY_FIRST: 'POST_DAILY_FIRST',
  POST_COMMENT_DAILY: 'POST_COMMENT_DAILY'
};

exports.PostContentType = exports.$Enums.PostContentType = {
  NORMAL: 'NORMAL',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  POLL: 'POLL',
  ARTICLE: 'ARTICLE'
};

exports.PostStatus = exports.$Enums.PostStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  LOCKED: 'LOCKED',
  DELETED: 'DELETED'
};

exports.MediaType = exports.$Enums.MediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO'
};

exports.ProfileWallVisibility = exports.$Enums.ProfileWallVisibility = {
  PUBLIC: 'PUBLIC',
  FRIENDS: 'FRIENDS',
  CLOSED: 'CLOSED'
};

exports.ReportTargetType = exports.$Enums.ReportTargetType = {
  POST: 'POST',
  REPLY: 'REPLY',
  USER: 'USER',
  MESSAGE: 'MESSAGE',
  DAILY_MESSAGE: 'DAILY_MESSAGE',
  DAILY_MESSAGE_COMMENT: 'DAILY_MESSAGE_COMMENT'
};

exports.ReportStatus = exports.$Enums.ReportStatus = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
};

exports.SiteSettingValueType = exports.$Enums.SiteSettingValueType = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  JSON: 'JSON',
  BOOLEAN: 'BOOLEAN',
  NUMBER: 'NUMBER'
};

exports.SystemNotificationType = exports.$Enums.SystemNotificationType = {
  SYSTEM: 'SYSTEM',
  UPDATE: 'UPDATE',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ACTIVITY: 'ACTIVITY',
  MAINTENANCE: 'MAINTENANCE',
  SECURITY: 'SECURITY'
};

exports.UserRole = exports.$Enums.UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
  MUTED: 'MUTED',
  DELETED: 'DELETED',
  MERGED: 'MERGED',
  DISABLED: 'DISABLED'
};

exports.VerificationStatus = exports.$Enums.VerificationStatus = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED'
};

exports.Prisma.ModelName = {
  AccountSecurityLog: 'AccountSecurityLog',
  Achievement: 'Achievement',
  Activity: 'Activity',
  ActivityFavorite: 'ActivityFavorite',
  ActivityRegistration: 'ActivityRegistration',
  AdminAction: 'AdminAction',
  AdminActionLog: 'AdminActionLog',
  AdminPermission: 'AdminPermission',
  Announcement: 'Announcement',
  Badge: 'Badge',
  Banner: 'Banner',
  Block: 'Block',
  Board: 'Board',
  BoardCategory: 'BoardCategory',
  BoardFavorite: 'BoardFavorite',
  Changelog: 'Changelog',
  CheckIn: 'CheckIn',
  Conversation: 'Conversation',
  ConversationParticipant: 'ConversationParticipant',
  CultureComment: 'CultureComment',
  CultureFavorite: 'CultureFavorite',
  CultureItem: 'CultureItem',
  DailyExperienceRecord: 'DailyExperienceRecord',
  DailyMessage: 'DailyMessage',
  DailyMessageComment: 'DailyMessageComment',
  DailyMessageFavorite: 'DailyMessageFavorite',
  DailyMessageLike: 'DailyMessageLike',
  DailyQuote: 'DailyQuote',
  DailyTaskProgress: 'DailyTaskProgress',
  DailyTaskTemplate: 'DailyTaskTemplate',
  DirectMessage: 'DirectMessage',
  EmailVerification: 'EmailVerification',
  EntertainmentDailyDraw: 'EntertainmentDailyDraw',
  ExperienceLog: 'ExperienceLog',
  Feedback: 'Feedback',
  FeedbackAttachment: 'FeedbackAttachment',
  FeedbackReply: 'FeedbackReply',
  Follow: 'Follow',
  FriendActivity: 'FriendActivity',
  FriendRequest: 'FriendRequest',
  Friendship: 'Friendship',
  GrowthLevelConfig: 'GrowthLevelConfig',
  GuessSongAudioVariant: 'GuessSongAudioVariant',
  GuessSongLeaderboardEntry: 'GuessSongLeaderboardEntry',
  GuessSongPlayRequest: 'GuessSongPlayRequest',
  GuessSongQuestion: 'GuessSongQuestion',
  GuessSongSession: 'GuessSongSession',
  GuessSongSessionQuestion: 'GuessSongSessionQuestion',
  Like: 'Like',
  LoginDevice: 'LoginDevice',
  Lottery: 'Lottery',
  LotteryEntry: 'LotteryEntry',
  LotteryPrize: 'LotteryPrize',
  LyricCard: 'LyricCard',
  LyricCardTemplate: 'LyricCardTemplate',
  LyricPrescription: 'LyricPrescription',
  MusicAlbum: 'MusicAlbum',
  MusicFavorite: 'MusicFavorite',
  MusicPlayRecord: 'MusicPlayRecord',
  MusicSong: 'MusicSong',
  MusicTrack: 'MusicTrack',
  Notification: 'Notification',
  OnlineSession: 'OnlineSession',
  PageLayout: 'PageLayout',
  PageLayoutRevision: 'PageLayoutRevision',
  PasswordResetToken: 'PasswordResetToken',
  PointLog: 'PointLog',
  Poll: 'Poll',
  PollOption: 'PollOption',
  PollVote: 'PollVote',
  Post: 'Post',
  PostFavorite: 'PostFavorite',
  PostMedia: 'PostMedia',
  PostTag: 'PostTag',
  Profile: 'Profile',
  ProfileWallLike: 'ProfileWallLike',
  ProfileWallMessage: 'ProfileWallMessage',
  RateLimitLog: 'RateLimitLog',
  Reply: 'Reply',
  ReplyLike: 'ReplyLike',
  Report: 'Report',
  SearchHistory: 'SearchHistory',
  SearchKeyword: 'SearchKeyword',
  SensitiveWord: 'SensitiveWord',
  SiteSetting: 'SiteSetting',
  SmsCode: 'SmsCode',
  SystemNotification: 'SystemNotification',
  SystemNotificationRead: 'SystemNotificationRead',
  Tag: 'Tag',
  Task: 'Task',
  User: 'User',
  UserAchievement: 'UserAchievement',
  UserAlbumCollection: 'UserAlbumCollection',
  UserBadge: 'UserBadge',
  UserSecurityQuestion: 'UserSecurityQuestion'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
