import { buildV6CoursePack } from './build'
import { V6_CANDIDATE_STATUS, type V6ContentDraft, type V6QuestionDraft } from './types'

const content: V6ContentDraft[] = [
  { key: 'intro', section: '01-場景介紹', contentType: 'CONCEPT', title: '先問地方，再確認路線', text: '問路先用禮貌開場，聽方向時分辨直行、轉彎和過馬路。', meaning: '学习在香港问路', explanation: '本课分为步行方向、时间距离和乘车确认；地名与实际路线仅作情境，不构成真实导航建议。' },
  { key: 'station', section: '02-關鍵詞', contentType: 'WORD', title: '地鐵站', text: '地鐵站', jyutping: 'dei6 tit3 zaam6', meaning: '港铁车站', explanation: '询问车站位置时使用；实际港铁线路以现场信息为准。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/地鐵站' },
  { key: 'where', section: '02-關鍵詞', contentType: 'WORD', title: '邊度', text: '邊度', jyutping: 'bin1 dou6', meaning: '哪里', explanation: '问位置的常见口语词。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/度' },
  { key: 'how', section: '02-關鍵詞', contentType: 'WORD', title: '點樣', text: '點樣', jyutping: 'dim2 joeng2', meaning: '怎样', explanation: '问方法或路线，需与「邊度」区别。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/點' },
  { key: 'straight', section: '02-關鍵詞', contentType: 'WORD', title: '一直行', text: '一直行', meaning: '一直走', explanation: '表示沿目前方向继续步行；整句粤拼待人工确认。', requiresAudio: true, requiresSpeaking: true },
  { key: 'left', section: '02-關鍵詞', contentType: 'WORD', title: '轉左', text: '轉左', meaning: '向左转', explanation: '与「轉右」形成最基本的方向对比。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/轉' },
  { key: 'right', section: '02-關鍵詞', contentType: 'WORD', title: '轉右', text: '轉右', meaning: '向右转', explanation: '听清左、右，再确认路口位置。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/轉' },
  { key: 'cross', section: '02-關鍵詞', contentType: 'WORD', title: '過馬路', text: '過馬路', meaning: '过马路', explanation: '涉及安全时以实际交通灯和路况为准。', requiresAudio: true },
  { key: 'next-stop', section: '02-關鍵詞', contentType: 'WORD', title: '下一站', text: '下一站', meaning: '下一站', explanation: '乘车时询问或确认站名。', requiresAudio: true },
  { key: 'where-station', section: '03-核心句型', contentType: 'SENTENCE', title: '唔好意思，地鐵站喺邊度？', text: '唔好意思，地鐵站喺邊度？', meaning: '不好意思，地铁站在哪里？', explanation: '向陌生人问路先用礼貌开场。', requiresAudio: true, requiresSpeaking: true },
  { key: 'how-go', section: '03-核心句型', contentType: 'SENTENCE', title: '請問點樣去地鐵站？', text: '請問點樣去地鐵站？', meaning: '请问怎样去地铁站？', explanation: '重点是问路线，而不只问地点。', requiresAudio: true, requiresSpeaking: true },
  { key: 'how-long', section: '03-核心句型', contentType: 'SENTENCE', title: '行過去要幾耐？', text: '行過去要幾耐？', meaning: '走过去要多久？', explanation: '在听过方向之后询问步行时间。', requiresAudio: true, requiresSpeaking: true },
  { key: 'bus-go', section: '03-核心句型', contentType: 'SENTENCE', title: '呢架車去唔去旺角？', text: '呢架車去唔去旺角？', meaning: '这辆车去不去旺角？', explanation: '上车前核对方向与目的地；实际班次须现场确认。', requiresAudio: true, requiresSpeaking: true },
  { key: 'please-repeat', section: '03-核心句型', contentType: 'SENTENCE', title: '唔該，可唔可以講多次？', text: '唔該，可唔可以講多次？', meaning: '劳驾，可以再说一次吗？', explanation: '没听清指路时主动确认，避免误走。', requiresAudio: true, requiresSpeaking: true },
  { key: 'direction-contrast', section: '03-核心句型', contentType: 'CONTRAST', title: '邊度與點樣', text: '喺邊度？／點樣去？', meaning: '位置／方法', explanation: '「喺邊度」偏重位置；「點樣去」偏重走法。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/度 ; https://words.hk/zidin/點' },
  { key: 'junction-phrase', section: '03-核心短語', contentType: 'PHRASE', title: '前面個路口', text: '前面個路口', meaning: '前面的路口', explanation: '常与「轉左／轉右」组合，形成清楚的方向提示；粤拼待人工核对。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/路口' },
  { key: 'd1a', section: '04-真實對話', contentType: 'DIALOGUE', title: '尋找車站 · A', text: '唔好意思，地鐵站喺邊度？', meaning: '不好意思，港铁站在哪里？', explanation: '先礼貌开场。', requiresAudio: true, dialogueId: 'station-walk', speaker: 'A' },
  { key: 'd1b', section: '04-真實對話', contentType: 'DIALOGUE', title: '尋找車站 · B', text: '一直行，前面個路口轉左。', meaning: '一直走，在前面路口左转。', explanation: '先直走再左转。', requiresAudio: true, dialogueId: 'station-walk', speaker: 'B' },
  { key: 'd1c', section: '04-真實對話', contentType: 'DIALOGUE', title: '尋找車站 · A', text: '係咪過咗馬路就到？', meaning: '是不是过了马路就到了？', explanation: '复述关键信息以确认。', requiresAudio: true, dialogueId: 'station-walk', speaker: 'A' },
  { key: 'd1d', section: '04-真實對話', contentType: 'DIALOGUE', title: '尋找車站 · B', text: '係，過咗馬路就見到。', meaning: '是，过马路就看见。', explanation: '确认目的地。', requiresAudio: true, dialogueId: 'station-walk', speaker: 'B' },
  { key: 'd1e', section: '04-真實對話', contentType: 'DIALOGUE', title: '尋找車站 · A', text: '唔該晒！', meaning: '十分感谢。', explanation: '向指路者道谢。', requiresAudio: true, dialogueId: 'station-walk', speaker: 'A' },
  { key: 'd2a', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認時間 · A', text: '行過去要幾耐？', meaning: '走过去要多久？', explanation: '问步行耗时。', requiresAudio: true, dialogueId: 'walking-time', speaker: 'A' },
  { key: 'd2b', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認時間 · B', text: '大概十分鐘。', meaning: '大约十分钟。', explanation: '时间是对话示例，不是实际地理承诺。', requiresAudio: true, dialogueId: 'walking-time', speaker: 'B' },
  { key: 'd2c', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認時間 · A', text: '一直行，定係要轉彎？', meaning: '一直走，还是要转弯？', explanation: '分辨路线是否需要转向。', requiresAudio: true, dialogueId: 'walking-time', speaker: 'A' },
  { key: 'd2d', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認時間 · B', text: '行到個路口轉右。', meaning: '走到路口右转。', explanation: '给出路口和方向两项信息。', requiresAudio: true, dialogueId: 'walking-time', speaker: 'B' },
  { key: 'd3a', section: '04-真實對話', contentType: 'DIALOGUE', title: '上車前確認 · A', text: '唔該，呢架車去唔去旺角？', meaning: '劳驾，这辆车去不去旺角？', explanation: '上车前确认目的地。', requiresAudio: true, dialogueId: 'on-bus', speaker: 'A' },
  { key: 'd3b', section: '04-真實對話', contentType: 'DIALOGUE', title: '上車前確認 · B', text: '去，你可以上車。', meaning: '去，你可以上车。', explanation: '对话示例；实际路线仍须以现场信息为准。', requiresAudio: true, dialogueId: 'on-bus', speaker: 'B' },
  { key: 'd3c', section: '04-真實對話', contentType: 'DIALOGUE', title: '上車前確認 · A', text: '請問喺邊個站落車？', meaning: '请问在哪一站下车？', explanation: '进一步确认下车站。', requiresAudio: true, dialogueId: 'on-bus', speaker: 'A' },
  { key: 'd3d', section: '04-真實對話', contentType: 'DIALOGUE', title: '上車前確認 · B', text: '我唔肯定，你睇下車上面嘅站牌。', meaning: '我不确定，请看车上的站牌。', explanation: '不知道时不编造路线。', requiresAudio: true, dialogueId: 'on-bus', speaker: 'B' },
  { key: 'd4a', section: '04-真實對話', contentType: 'DIALOGUE', title: '沒聽清路線 · A', text: '唔該，可唔可以講多次？', meaning: '劳驾，可以再说一次吗？', explanation: '请对方重复。', requiresAudio: true, requiresSpeaking: true, dialogueId: 'repeat', speaker: 'A' },
  { key: 'd4b', section: '04-真實對話', contentType: 'DIALOGUE', title: '沒聽清路線 · B', text: '一直行，第二個路口轉左。', meaning: '一直走，在第二个路口左转。', explanation: '再次说清路线。', requiresAudio: true, dialogueId: 'repeat', speaker: 'B' },
  { key: 'd4c', section: '04-真實對話', contentType: 'DIALOGUE', title: '沒聽清路線 · A', text: '第二個路口轉左，係咪？', meaning: '第二个路口左转，对吗？', explanation: '复述确认，避免左、右听错。', requiresAudio: true, requiresSpeaking: true, dialogueId: 'repeat', speaker: 'A' },
  { key: 'd4d', section: '04-真實對話', contentType: 'DIALOGUE', title: '沒聽清路線 · B', text: '係，行多陣就到。', meaning: '对，再走一会儿就到了。', explanation: '回应确认。', requiresAudio: true, dialogueId: 'repeat', speaker: 'B' },
  { key: 'review', section: '08-回顧', contentType: 'SUMMARY', title: '問路回顧', text: '問位置、聽方向、複述確認。', meaning: '复习', explanation: '问路时确认左、右、路口和时间；本课不提供真实导航服务。' },
]

const questions: V6QuestionDraft[] = [
  { key: 'where-vs-how', questionType: 'SINGLE_SELECT', prompt: '只想问港铁站的位置，选哪句？', options: ['地鐵站喺邊度？', '點樣去地鐵站？', '行過去要幾耐？', '喺邊個站落車？'], correct: [0], explanation: '几句都与出行有关；「喺邊度」最直接询问地点。', prerequisites: ['where', 'where-station', 'how-go', 'how-long', 'd3c'] },
  { key: 'how-route', questionType: 'SINGLE_SELECT', prompt: '想知道去港铁站的走法，选哪句？', options: ['點樣去地鐵站？', '地鐵站喺邊度？', '行過去要幾耐？', '喺邊個站落車？'], correct: [0], explanation: '「點樣去」问方法或路线，不是只问位置、时间或下车站。', prerequisites: ['how', 'how-go', 'where-station', 'how-long', 'd3c'] },
  { key: 'left', questionType: 'SINGLE_SELECT', prompt: '对方说「轉左」，你应往哪边？', options: ['左边', '右边', '直走不转', '原路返回'], correct: [0], explanation: '左、右不可混淆。', prerequisites: ['left', 'right'] },
  { key: 'right', questionType: 'SINGLE_SELECT', prompt: '哪句包含「右转」的意思？', options: ['行到個路口轉右。', '前面個路口轉左。', '一直行唔使轉。', '過咗馬路就見到。'], correct: [0], explanation: '「轉右」表示右转。', prerequisites: ['right', 'd2d'] },
  { key: 'duration', questionType: 'SINGLE_SELECT', prompt: '想问步行需要多久，哪句合适？', options: ['行過去要幾耐？', '點樣去地鐵站？', '喺邊個站落車？', '第二個路口轉左，係咪？'], correct: [0], explanation: '「幾耐」这里问时长；其余问路线、站名或核对方向。', prerequisites: ['how-long', 'how-go', 'd3c', 'd4c'] },
  { key: 'bus-check', questionType: 'SINGLE_SELECT', prompt: '上车前想确认这条车线是否到旺角，选哪句？', options: ['呢架車去唔去旺角？', '點樣去旺角？', '行過去要幾耐？', '喺邊個站落車？'], correct: [0], explanation: 'A 直接确认这条车线是否前往目的地；B 问去旺角的方法，C 问步行时间，D 问下车站。', prerequisites: ['bus-go', 'next-stop', 'how-long', 'where'] },
  { key: 'repeat', questionType: 'SINGLE_SELECT', prompt: '没听清方向，应怎样礼貌请对方重说？', options: ['唔該，可唔可以講多次？', '一直行，前面轉左。', '下一站喺旺角落車。', '過咗馬路就到。'], correct: [0], explanation: '其他选项是路线信息，不是请对方重复；听不清时应先核对。', prerequisites: ['please-repeat'] },
  { key: 'verify-left', questionType: 'SINGLE_SELECT', prompt: '对方说第二个路口左转，哪句是在核对信息？', options: ['第二個路口轉左，係咪？', '一直行，定係要轉彎？', '呢架車去唔去旺角？', '我唔肯定。'], correct: [0], explanation: '复述路口和方向并以「係咪」确认。', prerequisites: ['d4b', 'd4c'] },
  { key: 'unknown-route', questionType: 'SINGLE_SELECT', prompt: '如果你不确定车是否到某站，哪种回应较安全？', options: ['坦白不确定，并请对方看站牌', '估计是同一条线，叫对方先上车再看', '凭上次乘车印象回答，不再核对', '说「应该会到」，但不确认站名'], correct: [0], explanation: '真实出行信息应核对；凭印象猜测或给出含糊承诺都可能误导乘客。', prerequisites: ['d3d'] },
  { key: 'direction-multi', questionType: 'MULTI_SELECT', prompt: '哪些属于步行方向信息？（多选）', options: ['一直行', '轉左', '轉右', '坐地鐵去下一站'], correct: [0, 1, 2], explanation: '直行、左转、右转都是步行路线信息；乘地铁属于交通方式。', prerequisites: ['straight', 'left', 'right'] },
  { key: 'safety-multi', questionType: 'MULTI_SELECT', prompt: '问路时哪些做法有助于确认路线？（多选）', options: ['听不清就请对方再说一次', '复述左右方向', '乘车前看站牌', '不看交通灯直接横穿马路'], correct: [0, 1, 2], explanation: '不确定时多确认，过马路仍须遵守交通规则。', prerequisites: ['please-repeat', 'd4c', 'd3d', 'cross'] },
  { key: 'where-true', questionType: 'TRUE_FALSE', prompt: '「喺邊度」可用于问某个地点在哪里。', options: ['正确', '错误'], correct: [0], explanation: '这是地点问句。', prerequisites: ['where', 'where-station'] },
  { key: 'route-false', questionType: 'TRUE_FALSE', prompt: '课程对话中的示例车次和时长可以直接作为现实导航承诺。', options: ['正确', '错误'], correct: [1], explanation: '出行须核对即时路线、班次与路况。', prerequisites: ['intro', 'd2b', 'd3d'] },
  { key: 'listen-left', questionType: 'LISTENING', prompt: '听标准音，选择对方指示的方向。', options: ['左转', '右转', '坐车', '回头'], correct: [0], explanation: '标准音绑定「一直行，前面個路口轉左」。', prerequisites: ['d1b'], audioFrom: 'd1b' },
  { key: 'listen-right', questionType: 'LISTENING', prompt: '听标准音，选出对方说的路线。', options: ['到路口右转', '到路口左转', '过桥后下车', '原路返回'], correct: [0], explanation: '标准音绑定「行到個路口轉右」。', prerequisites: ['d2d'], audioFrom: 'd2d' },
  { key: 'listen-time', questionType: 'LISTENING', prompt: '听标准音，对方说步行大概多久？', options: ['十分钟', '五分钟', '半小时', '没说'], correct: [0], explanation: '听示例回答；非真实地理时长。', prerequisites: ['d2b'], audioFrom: 'd2b' },
  { key: 'speak-station', questionType: 'SPEAKING', prompt: '情景：礼貌问陌生人港铁站在哪里。听标准音、录音并自行比较。', options: [], correct: [], explanation: '本机录音 A/B 比较，不评分。', prerequisites: ['where-station'], audioFrom: 'where-station', speakingFrom: 'where-station' },
  { key: 'speak-repeat', questionType: 'SPEAKING', prompt: '情景：没听清路线。跟读礼貌地请对方再说一次。', options: [], correct: [], explanation: '重点练礼貌请求，不上传语音。', prerequisites: ['d4a'], audioFrom: 'd4a', speakingFrom: 'd4a' },
  { key: 'challenge-start', questionType: 'SINGLE_SELECT', prompt: '情景挑战：你迷路了，想先问港铁站在哪里，哪句最切合？', options: ['唔好意思，請問港鐵站喺邊度？', '唔該，可唔可以講多次？', '呢架車去唔去旺角？', '行過去要幾耐？'], correct: [0], explanation: '先礼貌询问目标地点；其他选项分别是请人重说、确认车线和询问步行时间。', prerequisites: ['where-station', 'd1a', 'please-repeat', 'bus-go', 'how-long'] },
  { key: 'challenge-understand', questionType: 'SINGLE_SELECT', prompt: '情景挑战：听到「一直行，第二個路口轉左」，应该怎样走？', options: ['先直走，在第二个路口左转', '第一个路口右转', '直接上车', '过马路后立刻回头'], correct: [0], explanation: '把动作次序和第几个路口都听完整。', prerequisites: ['straight', 'left', 'd4b'] },
]

export const LESSON_06_DIRECTIONS = buildV6CoursePack(
  { lessonId: 'lesson-06', lessonNumber: 6, title: '問路與出行', subtitle: '問位置、聽方向、再確認', description: '練習步行問路、時間距離及上車前確認。', sortOrder: 6, prerequisiteLessonId: 'lesson-05', status: V6_CANDIDATE_STATUS, reviewStatus: V6_CANDIDATE_STATUS },
  'directions-travel', content, questions,
  { 'station-walk': '尋找車站', 'walking-time': '確認步行時間', 'on-bus': '上車前確認', repeat: '沒聽清路線' },
)
