import { buildV6CoursePack } from './build'
import { V6_CANDIDATE_STATUS, type V6ContentDraft, type V6QuestionDraft } from './types'

const content: V6ContentDraft[] = [
  { key: 'intro', section: '01-場景介紹', contentType: 'CONCEPT', title: '從入座到埋單', text: '先說人數與堂食或外賣，再下單、確認口味，最後埋單。', meaning: '餐厅点餐流程', explanation: '不同餐厅的服务流程、支付方式和用词可能不同；示例须由香港粤语审核员确认。' },
  { key: 'dine-in', section: '02-關鍵詞', contentType: 'WORD', title: '堂食', text: '堂食', meaning: '店内用餐', explanation: '与「外賣」相对。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/堂食' },
  { key: 'takeaway', section: '02-關鍵詞', contentType: 'WORD', title: '外賣', text: '外賣', meaning: '外带／外卖', explanation: '说明不在店内吃；与堂食的具体店内用法须审核。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/外賣' },
  { key: 'take-away-action', section: '02-關鍵詞', contentType: 'WORD', title: '拎走', text: '拎走', meaning: '拿走／带走', explanation: '与「外賣」相关但用法和句式位置可能不同；例句及语境须由审核员确认。', requiresAudio: true, requiresSpeaking: true },
  { key: 'order', section: '02-關鍵詞', contentType: 'WORD', title: '落單', text: '落單', meaning: '下单', explanation: '点好餐后向店员下单。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/落單' },
  { key: 'bill', section: '02-關鍵詞', contentType: 'WORD', title: '埋單', text: '埋單', jyutping: 'maai4 daan1', meaning: '结账', explanation: '吃完后请求结账。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/埋單' },
  { key: 'less-ice', section: '02-關鍵詞', contentType: 'WORD', title: '少冰', text: '少冰', meaning: '少放冰', explanation: '饮品冰量要求；和「走冰」不同。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/冰' },
  { key: 'no-ice', section: '02-關鍵詞', contentType: 'WORD', title: '走冰', text: '走冰', jyutping: 'zau2 bing1', meaning: '不加冰', explanation: '点饮品时要求不加冰。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://www.cantonese.sheik.co.uk/dictionary/words/17572/' },
  { key: 'less-sweet', section: '02-關鍵詞', contentType: 'WORD', title: '少甜', text: '少甜', meaning: '甜度少一点', explanation: '并非每种饮品都能调甜度，应先询问店员。', requiresAudio: true },
  { key: 'no-sweet', section: '02-關鍵詞', contentType: 'WORD', title: '走甜', text: '走甜', meaning: '不加糖／不加甜味', explanation: '与「少甜」的差别及实际点单习惯须由粤语审核员确认。', requiresAudio: true, requiresSpeaking: true },
  { key: 'sweetness-contrast', section: '03-核心句型', contentType: 'CONTRAST', title: '少甜與走甜', text: '少甜／走甜', meaning: '减少甜度／不加甜味', explanation: '暂按「减少」与「不加」作对比示例；各店可调整选项不同，须经语言审核。', requiresAudio: true },
  { key: 'not-spicy', section: '02-關鍵詞', contentType: 'WORD', title: '唔要辣', text: '唔要辣', meaning: '不要辣', explanation: '点餐时说明口味；具体菜品能否调整应询问店员。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/辣' },
  { key: 'iced-lemon-tea', section: '02-關鍵詞', contentType: 'WORD', title: '凍檸茶', text: '凍檸茶', jyutping: 'dung3 ning2 caa4', meaning: '冰柠檬茶', explanation: '香港常见饮品之一。', requiresAudio: true, sourceReference: 'https://words.hk/zidin/檸茶' },
  { key: 'two-people', section: '03-核心句型', contentType: 'SENTENCE', title: '兩位，唔該。', text: '兩位，唔該。', meaning: '两位，谢谢／劳驾。', explanation: '进店时告知人数，语气须人工审核。', requiresAudio: true, requiresSpeaking: true },
  { key: 'want-this', section: '03-核心句型', contentType: 'SENTENCE', title: '我想要呢個。', text: '我想要呢個。', meaning: '我想要这个。', explanation: '指着菜单明确点选，可再说出菜名避免误会。', requiresAudio: true, requiresSpeaking: true },
  { key: 'order-drink', section: '03-核心句型', contentType: 'SENTENCE', title: '一杯凍檸茶，少冰，唔該。', text: '一杯凍檸茶，少冰，唔該。', meaning: '一杯冰柠檬茶，少冰，劳驾。', explanation: '点饮品时说清冰量；具体制作方式仍以店员答复为准。', requiresAudio: true, requiresSpeaking: true },
  { key: 'spicy-check', section: '03-核心句型', contentType: 'SENTENCE', title: '呢個辣唔辣？', text: '呢個辣唔辣？', meaning: '这个辣不辣？', explanation: '先问菜品辣度，不能仅凭名字推断。', requiresAudio: true, requiresSpeaking: true },
  { key: 'bill-please', section: '03-核心句型', contentType: 'SENTENCE', title: '唔該，埋單。', text: '唔該，埋單。', meaning: '劳驾，结账。', explanation: '餐后向店员提出结账请求。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/埋單' },
  { key: 'ice-contrast', section: '03-核心句型', contentType: 'CONTRAST', title: '少冰與走冰', text: '少冰／走冰', meaning: '少放冰／不放冰', explanation: '两种要求不同；如果饮品本身以冰为特征，可重新确认店员是否能制作。', requiresAudio: true },
  { key: 'less-ice-phrase', section: '03-核心短語', contentType: 'PHRASE', title: '少冰，唔該', text: '少冰，唔該', jyutping: 'siu2 bing1 m4 goi1', meaning: '少放冰，谢谢／劳驾', explanation: '点饮品时提出冰量要求；具体读音与餐饮语境仍须审核。', requiresAudio: true, requiresSpeaking: true, sourceReference: 'https://words.hk/zidin/冰 ; https://words.hk/zidin/唔該' },
  { key: 'd1a', section: '04-真實對話', contentType: 'DIALOGUE', title: '進店 · 店員', text: '幾多位？', meaning: '几位？', explanation: '店员询问人数。', requiresAudio: true, dialogueId: 'seating', speaker: 'A' },
  { key: 'd1b', section: '04-真實對話', contentType: 'DIALOGUE', title: '進店 · 顧客', text: '兩位，唔該。', meaning: '两位，劳驾。', explanation: '说明人数。', requiresAudio: true, dialogueId: 'seating', speaker: 'B' },
  { key: 'd1c', section: '04-真實對話', contentType: 'DIALOGUE', title: '進店 · 店員', text: '堂食定外賣？', meaning: '堂食还是外带？', explanation: '区分用餐方式。', requiresAudio: true, dialogueId: 'seating', speaker: 'A' },
  { key: 'd1d', section: '04-真實對話', contentType: 'DIALOGUE', title: '進店 · 顧客', text: '堂食，唔該。', meaning: '堂食，劳驾。', explanation: '确认店内用餐。', requiresAudio: true, dialogueId: 'seating', speaker: 'B' },
  { key: 'd2a', section: '04-真實對話', contentType: 'DIALOGUE', title: '點餐 · 顧客', text: '我想要呢個，仲有一杯凍檸茶。', meaning: '我要这个，还有一杯冰柠檬茶。', explanation: '同时点食物和饮品。', requiresAudio: true, dialogueId: 'ordering', speaker: 'A' },
  { key: 'd2b', section: '04-真實對話', contentType: 'DIALOGUE', title: '點餐 · 店員', text: '杯嘢飲要唔要少冰？', meaning: '饮品要不要少冰？', explanation: '店员确认冰量。', requiresAudio: true, dialogueId: 'ordering', speaker: 'B' },
  { key: 'd2c', section: '04-真實對話', contentType: 'DIALOGUE', title: '點餐 · 顧客', text: '少冰就得，唔該。', meaning: '少冰就可以，谢谢。', explanation: '选择少冰而非走冰。', requiresAudio: true, dialogueId: 'ordering', speaker: 'A' },
  { key: 'd2d', section: '04-真實對話', contentType: 'DIALOGUE', title: '點餐 · 店員', text: '好，仲要唔要其他嘢？', meaning: '好，还要别的吗？', explanation: '确认是否加单。', requiresAudio: true, dialogueId: 'ordering', speaker: 'B' },
  { key: 'd2e', section: '04-真實對話', contentType: 'DIALOGUE', title: '加單 · 顧客', text: '唔該，我想加多一份。', meaning: '劳驾，我想再加一份。', explanation: '顾客回应店员的加单确认；具体表达仍须审核。', requiresAudio: true, requiresSpeaking: true, dialogueId: 'ordering', speaker: 'A' },
  { key: 'd3a', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認口味 · 顧客', text: '呢個辣唔辣？', meaning: '这个辣不辣？', explanation: '先确认口味。', requiresAudio: true, dialogueId: 'spice', speaker: 'A' },
  { key: 'd3b', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認口味 · 店員', text: '有少少辣。', meaning: '有一点辣。', explanation: '店员说明程度；示例并非任何菜品承诺。', requiresAudio: true, dialogueId: 'spice', speaker: 'B' },
  { key: 'd3c', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認口味 · 顧客', text: '可唔可以唔要辣？', meaning: '可以不要辣吗？', explanation: '询问是否能调整。', requiresAudio: true, requiresSpeaking: true, dialogueId: 'spice', speaker: 'A' },
  { key: 'd3d', section: '04-真實對話', contentType: 'DIALOGUE', title: '確認口味 · 店員', text: '我幫你問下廚房。', meaning: '我帮你问一下厨房。', explanation: '能否调整要向厨房确认，不应直接保证。', requiresAudio: true, dialogueId: 'spice', speaker: 'B' },
  { key: 'd4a', section: '04-真實對話', contentType: 'DIALOGUE', title: '埋單 · 顧客', text: '唔該，埋單。', meaning: '劳驾，结账。', explanation: '提出结账。', requiresAudio: true, dialogueId: 'payment', speaker: 'A' },
  { key: 'd4b', section: '04-真實對話', contentType: 'DIALOGUE', title: '埋單 · 店員', text: '好，請等一陣。', meaning: '好，请稍等。', explanation: '店员回应。', requiresAudio: true, dialogueId: 'payment', speaker: 'B' },
  { key: 'd4c', section: '04-真實對話', contentType: 'DIALOGUE', title: '埋單 · 顧客', text: '可唔可以用八達通？', meaning: '可以用八达通吗？', explanation: '先确认店铺支持的支付方式。', requiresAudio: true, requiresSpeaking: true, dialogueId: 'payment', speaker: 'A' },
  { key: 'd4d', section: '04-真實對話', contentType: 'DIALOGUE', title: '埋單 · 店員', text: '我睇下呢度收唔收。', meaning: '我看一下这里收不收。', explanation: '并非所有餐厅都接受同一种支付方式。', requiresAudio: true, dialogueId: 'payment', speaker: 'B' },
  { key: 'self-compare', section: '06-跟讀', contentType: 'SPEAKING_PRACTICE', title: '自己比較：埋單', text: '唔該，埋單。', meaning: '练习结账请求', explanation: '标准音审核就绪后，本机录音并 A/B 回听；不评分。', requiresAudio: true, requiresSpeaking: true },
  { key: 'review', section: '08-回顧', contentType: 'SUMMARY', title: '點餐回顧', text: '人數、堂食外賣、口味、埋單。', meaning: '复习', explanation: '点餐时说清数量、冷热甜辣；遇到不能更改的餐品，应接受店员实际答复。' },
]

const questions: V6QuestionDraft[] = [
  { key: 'seating', questionType: 'SINGLE_SELECT', prompt: '店员问「幾多位？」，两个人应怎样回答？', options: ['兩位，唔該。', '堂食，唔該。', '外賣，唔該。', '我想要呢個。'], correct: [0], explanation: '先回答人数；堂食或外卖是下一步要确认的用餐方式。', prerequisites: ['d1a', 'd1b', 'd1c', 'want-this'] },
  { key: 'dine-or-take', questionType: 'SINGLE_SELECT', prompt: '想在店里吃，店员问「堂食定外賣？」时应选？', options: ['堂食', '外賣', '走冰', '埋單'], correct: [0], explanation: '堂食是店内用餐。', prerequisites: ['dine-in', 'takeaway', 'd1c'] },
  { key: 'takeaway', questionType: 'MULTI_SELECT', prompt: '哪些词语可用于表达外带／拿走相关意思？（多选）', options: ['外賣', '堂食', '拎走', '埋單'], correct: [0, 2], explanation: '两者都与外带场景有关，但句法位置与实际用法仍要结合语境；课程保留为审核候选。', prerequisites: ['takeaway', 'take-away-action', 'd1c'] },
  { key: 'point-menu', questionType: 'SINGLE_SELECT', prompt: '指着菜单想要其中一项，哪句是在点选菜品？', options: ['我想要呢個。', '呢個辣唔辣？', '呢個可唔可以唔要辣？', '呢個幾時上？'], correct: [0], explanation: '其他句子围绕同一菜品提问，但只有第一句明确点选。', prerequisites: ['want-this', 'spicy-check', 'd3c'] },
  { key: 'ice-difference', questionType: 'SINGLE_SELECT', prompt: '想完全不加冰，应说什么？', options: ['走冰', '少冰', '少甜', '堂食'], correct: [0], explanation: '「走冰」与「少冰」不同。', prerequisites: ['no-ice', 'ice-contrast'] },
  { key: 'sweetness', questionType: 'SINGLE_SELECT', prompt: '想表达甜度减少而不是完全不加甜味，哪一个更符合本课的对比？', options: ['少甜', '走甜', '少冰', '走冰'], correct: [0], explanation: '候选课程以「少甜／走甜」区分减少甜度与不加甜味；实际点单用法需人工确认。', prerequisites: ['less-sweet', 'no-sweet', 'sweetness-contrast'] },
  { key: 'spice-question', questionType: 'SINGLE_SELECT', prompt: '点餐前想确认辣度，选哪句？', options: ['呢個辣唔辣？', '可唔可以用八達通？', '堂食定外賣？', '幾多位？'], correct: [0], explanation: '先询问是否辣。', prerequisites: ['spicy-check'] },
  { key: 'spice-adjust', questionType: 'SINGLE_SELECT', prompt: '店员说有点辣，你希望不辣，下一句较合适？', options: ['可唔可以唔要辣？', '唔該埋單。', '少冰就得。', '可唔可以轉凍飲？'], correct: [0], explanation: '礼貌询问能否调整辣度；其他选项是在结账或调整饮品。', prerequisites: ['d3a', 'd3b', 'd3c'] },
  { key: 'bill', questionType: 'SINGLE_SELECT', prompt: '吃完准备付款时，应选哪句？', options: ['唔該，埋單。', '可唔可以用八達通？', '仲要唔要其他嘢？', '堂食，唔該。'], correct: [0], explanation: '先提出结账，再核对支付方式；其余分别是支付询问、加单确认和用餐方式。', prerequisites: ['bill', 'bill-please', 'd4c', 'd2d', 'd1d'] },
  { key: 'pay-method', questionType: 'SINGLE_SELECT', prompt: '不确定餐厅能否用八达通付款，怎样确认？', options: ['可唔可以用八達通？', '一定要收八達通。', '呢個辣唔辣？', '一杯凍檸茶。'], correct: [0], explanation: '支付方式要先问，不能默认。', prerequisites: ['d4c', 'd4d'] },
  { key: 'order-flow', questionType: 'MULTI_SELECT', prompt: '点餐前或点餐时应确认哪些信息？（多选）', options: ['人数与用餐方式', '菜品与数量', '饮品冰量或口味', '现实中的站牌'], correct: [0, 1, 2], explanation: '餐厅情景需确认人数、菜品和口味。', prerequisites: ['intro', 'd1a', 'd1c', 'd2a', 'd2b'] },
  { key: 'payment-multi', questionType: 'MULTI_SELECT', prompt: '哪些属于合理的结账行为？（多选）', options: ['说「唔該，埋單」', '先询问是否支持八达通', '假定任何店都支持同种支付方式', '等店员确认'], correct: [0, 1, 3], explanation: '先提出结账、核对支付方式并等待确认。', prerequisites: ['bill-please', 'd4b', 'd4c', 'd4d'] },
  { key: 'ice-false', questionType: 'TRUE_FALSE', prompt: '「少冰」和「走冰」都表示完全不放冰。', options: ['正确', '错误'], correct: [1], explanation: '少冰是少放，走冰是不放。', prerequisites: ['ice-contrast'] },
  { key: 'spice-true', questionType: 'TRUE_FALSE', prompt: '菜品能否改成不辣，应先问店员确认。', options: ['正确', '错误'], correct: [0], explanation: '能否调整由餐厅决定。', prerequisites: ['d3c', 'd3d'] },
  { key: 'listen-dine-in', questionType: 'LISTENING', prompt: '听标准音，顾客选了哪种用餐方式？', options: ['堂食', '外賣', '没有说明', '打包后留在店内'], correct: [0], explanation: '听顾客回答「堂食，唔該」。', prerequisites: ['d1d'], audioFrom: 'd1d' },
  { key: 'listen-ice', questionType: 'LISTENING', prompt: '听标准音，顾客选择了什么冰量？', options: ['少冰', '走冰', '加冰', '未提冰量'], correct: [0], explanation: '听「少冰就得，唔該」。', prerequisites: ['d2c'], audioFrom: 'd2c' },
  { key: 'listen-spicy', questionType: 'LISTENING', prompt: '听标准音，店员如何描述辣度？', options: ['有少少辣', '完全唔辣', '非常辣', '没有回答'], correct: [0], explanation: '听原句，不推断其他餐厅的菜品。', prerequisites: ['d3b'], audioFrom: 'd3b' },
  { key: 'speak-order', questionType: 'SPEAKING', prompt: '情景：指着菜单点一个菜。听标准音、录音并 A/B 回听。', options: [], correct: [], explanation: '本地录音自主对比，不上传、不评分。', prerequisites: ['want-this'], audioFrom: 'want-this', speakingFrom: 'want-this' },
  { key: 'speak-bill', questionType: 'SPEAKING', prompt: '情景：吃完想结账。听标准音、录音并 A/B 回听。', options: [], correct: [], explanation: '练习礼貌结账请求。', prerequisites: ['bill-please'], audioFrom: 'bill-please', speakingFrom: 'bill-please' },
  { key: 'challenge-sequence', questionType: 'SINGLE_SELECT', prompt: '情景挑战：进餐厅后，哪组顺序最合理？', options: ['说人数与堂食／外賣 → 点餐与口味 → 埋單', '埋單 → 再说人数 → 问路', '先问路 → 点餐 → 再进店', '先说走冰 → 离开 → 再看菜单'], correct: [0], explanation: '这是本课从入店到付款的流程。', prerequisites: ['intro', 'd1a', 'd1c', 'd2a', 'd4a'] },
]

export const LESSON_07_ORDERING = buildV6CoursePack(
  { lessonId: 'lesson-07', lessonNumber: 7, title: '餐廳點餐', subtitle: '由入座、口味到埋單', description: '在短對話中練習堂食外賣、飲品要求、確認辣度與付款。', sortOrder: 7, prerequisiteLessonId: 'lesson-06', status: V6_CANDIDATE_STATUS, reviewStatus: V6_CANDIDATE_STATUS },
  'restaurant-ordering', content, questions,
  { seating: '進店入座', ordering: '點餐與飲品', spice: '確認辣度', payment: '埋單與付款' },
)
