'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { AdminSongCatalog } from '@/app/admin/music/AdminSongCatalog'
import { MusicCoverUploader } from '@/app/admin/music/MusicCoverUploader'

type Album = { id: string; name: string; artist: string; releaseDate?: string | null; releaseYear: number; language: string; company?: string | null; description?: string | null; story?: string | null; status: 'DRAFT' | 'PUBLISHED'; displayOrder: number; isFeatured: boolean; featuredOrder?: number | null; coverUrl?: string | null }
const field = 'w-full rounded-2xl border border-sky-100 bg-white px-4 py-2.5 text-sm font-bold outline-none focus:border-brand-300'

export function AdminAlbumEditor({ albumId }: Readonly<{ albumId: string }>) {
  const [album, setAlbum] = useState<Album | null>(null)
  const [form, setForm] = useState({ albumName: '', artist: '', releaseDate: '', releaseYear: '', language: '', company: '', description: '', story: '', displayOrder: '0', status: 'DRAFT', isFeatured: false, featuredOrder: '0' })
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { const response = await fetch(`/api/admin/music/albums/${albumId}`); const data = await response.json().catch(() => null); if (!response.ok) return setError(data?.message || '专辑加载失败'); const item = data.album as Album; setAlbum(item); setForm({ albumName: item.name, artist: item.artist, releaseDate: item.releaseDate ? item.releaseDate.slice(0, 10) : '', releaseYear: String(item.releaseYear), language: item.language, company: item.company || '', description: item.description || '', story: item.story || '', displayOrder: String(item.displayOrder), status: item.status, isFeatured: item.isFeatured, featuredOrder: String(item.featuredOrder ?? 0) }) }, [albumId])
  useEffect(() => { void load() }, [load])
  async function save(event?: FormEvent, nextStatus?: 'DRAFT' | 'PUBLISHED') { event?.preventDefault(); if (busy) return; setBusy(true); setError(''); const response = await fetch(`/api/admin/music/albums/${albumId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, status: nextStatus || form.status }) }); const data = await response.json().catch(() => null); if (!response.ok) setError(data?.message || '保存失败'); else { setMessage(data.message); setAlbum(data.album); setForm((current) => ({ ...current, status: data.album.status })) } setBusy(false) }
  if (!album) return <main className="mx-auto max-w-6xl p-6"><p className="font-bold text-slate-500">{error || '正在加载专辑...'}</p></main>
  return <main className="mx-auto max-w-6xl space-y-7 px-4 py-7 sm:px-5"><section className="rounded-[30px] border border-sky-100 bg-white/90 p-6 shadow-sm"><Link href="/admin/music/albums" className="text-sm font-black text-brand-700">← 专辑管理</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-4xl font-black text-brand-950">{album.name}</h1><p className="mt-2 text-sm font-bold text-slate-500">{album.status === 'PUBLISHED' ? '已发布到前台' : '草稿，前台不可见'}</p></div><button type="button" onClick={() => void save(undefined, album.status === 'PUBLISHED' ? 'DRAFT' : 'PUBLISHED')} className={`rounded-full px-5 py-3 text-sm font-black text-white ${album.status === 'PUBLISHED' ? 'bg-amber-600' : 'bg-emerald-700'}`}>{album.status === 'PUBLISHED' ? '取消发布' : '发布专辑'}</button></div></section>
    {message ? <p className="rounded-2xl bg-emerald-50 p-3 text-sm font-black text-emerald-700">{message}</p> : null}{error ? <p className="rounded-2xl bg-red-50 p-3 text-sm font-black text-red-600">{error}</p> : null}
    <section className="grid gap-6 md:grid-cols-[320px_minmax(0,1fr)]"><MusicCoverUploader entityType="album" entityId={albumId} currentUrl={album.coverUrl} onUploaded={(url) => setAlbum({ ...album, coverUrl: url })} /><form onSubmit={(event) => void save(event)} className="rounded-[28px] border border-sky-100 bg-white/90 p-5 shadow-sm sm:p-7"><h2 className="text-2xl font-black text-brand-950">专辑资料</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={form.albumName} onChange={(e) => setForm({ ...form, albumName: e.target.value })} className={field} placeholder="专辑名称" /><input value={form.artist} onChange={(e) => setForm({ ...form, artist: e.target.value })} className={field} placeholder="艺术家" /><input required type="number" value={form.releaseYear} onChange={(e) => setForm({ ...form, releaseYear: e.target.value })} className={field} placeholder="发行年份" /><input type="date" value={form.releaseDate} onChange={(e) => setForm({ ...form, releaseDate: e.target.value })} className={field} /><input value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })} className={field} placeholder="语言" /><input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} className={field} placeholder="唱片公司" /><input type="number" min="0" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} className={field} placeholder="普通展示排序" /><label className={`${field} flex items-center gap-3`}><input type="checkbox" checked={form.isFeatured} onChange={(e) => setForm({ ...form, isFeatured: e.target.checked })} className="h-4 w-4" />设为精选专辑</label><input type="number" min="0" disabled={!form.isFeatured} value={form.featuredOrder} onChange={(e) => setForm({ ...form, featuredOrder: e.target.value })} className={`${field} disabled:bg-slate-50 disabled:text-slate-400`} placeholder="精选排序（越小越靠前）" /><div /><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className={`${field} min-h-28 sm:col-span-2`} placeholder="专辑介绍" /><textarea value={form.story} onChange={(e) => setForm({ ...form, story: e.target.value })} className={`${field} min-h-36 sm:col-span-2`} placeholder="专辑故事" /></div><button disabled={busy} className="mt-5 rounded-full bg-brand-950 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy ? '保存中...' : '保存专辑资料'}</button></form></section>
    <AdminSongCatalog lockedAlbumId={albumId} />
  </main>
}
