import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const root = process.cwd()
const read = (path: string) => readFileSync(`${root}/${path}`, 'utf8')

test('Anywhere Door responsive contract covers required mobile and desktop viewports', () => {
  const page = read('app/anywhere-door/page.tsx')
  const detail = read('app/anywhere-door/[postId]/page.tsx')
  const detailComponent = read('components/anywhere-door/AnywhereDoorDetail.tsx')
  const morePosts = read('components/anywhere-door/AnywhereDoorMorePosts.tsx')
  const carousel = read('components/anywhere-door/MediaCarousel.tsx')
  const card = read('components/anywhere-door/AnywhereDoorPostCard.tsx')
  const comments = read('components/anywhere-door/AnywhereDoorCommentPanel.tsx')
  const styles = read('app/globals.css')
  const requiredMobileWidths = [360, 390, 430]
  const requiredDesktopWidths = [1366, 1440, 1920]

  assert.deepEqual(requiredMobileWidths, [360, 390, 430])
  assert.deepEqual(requiredDesktopWidths, [1366, 1440, 1920])
  assert.match(page, /anywhere-door-page/)
  assert.match(page, /max-w-\[1480px\]/)
  assert.match(page, /px-3 py-4/)
  assert.match(page, /hidden lg:block/)
  assert.match(page, /lg:hidden/)
  assert.match(detail, /anywhere-door-page/)
  assert.match(detail, /max-w-\[1480px\]/)
  assert.match(detail, /px-3 py-4/)
  assert.match(detailComponent, /data-anywhere-door-detail-shell/)
  assert.match(detailComponent, /anywhere-door-main/)
  assert.match(detailComponent, /anywhere-door-media-viewer/)
  assert.match(detailComponent, /anywhere-door-comment-slot/)
  assert.match(detailComponent, /<AnywhereDoorCommentPanel embedded/)
  assert.match(detailComponent, /bg-black/)
  assert.match(morePosts, /data-anywhere-door-more-posts/)
  assert.match(morePosts, /anywhere-door-more-posts-panel/)
  assert.match(morePosts, /hidden min-w-0 lg:block/)
  assert.match(morePosts, /href=\{`\/anywhere-door\/\$\{post\.id\}`\}/)
  assert.match(morePosts, /object-cover/)
  assert.match(morePosts, /'▧' : '▶'/)
  assert.doesNotMatch(morePosts, />\{post\.mediaType\}<\/span>/)
  assert.match(carousel, /overflow-hidden/)
  assert.match(carousel, /bg-black/)
  assert.match(carousel, /anywhere-door-media-frame/)
  assert.match(carousel, /object-contain/)
  assert.doesNotMatch(carousel, />\{current\.type\}<\/span>/)
  assert.match(carousel, /aspect-square/)
  assert.match(carousel, /sm:aspect-\[4\/3\]/)
  assert.match(carousel, /lg:h-full lg:aspect-auto/)
  assert.match(comments, /break-words/)
  assert.match(comments, /加载更多评论/)
  assert.match(comments, /查看更多回复/)
  assert.match(comments, /anywhere-door-comments-embedded/)
  assert.match(comments, /anywhere-door-comment-list/)
  assert.match(comments, /lg:overflow-y-auto/)
  assert.match(comments, /overflow-visible[^']*lg:overflow-hidden/)
  assert.match(card, /p-0 sm:p-4/)
  assert.match(card, /px-3 pb-4 pt-4/)
  assert.match(comments, /data-anywhere-door-comments=\{embedded \? 'embedded' : 'standalone'\}/)
  assert.match(detailComponent, /dark:bg-slate-900\/90/)
  assert.match(styles, /\.anywhere-door-page \{[\s\S]*max-width: 1480px;/)
  assert.match(styles, /\.anywhere-door-main \{[\s\S]*height: clamp\(520px, calc\(100dvh - 112px\), 800px\)/)
  assert.match(styles, /grid-template-columns: minmax\(0, 1\.8fr\) minmax\(300px, 0\.95fr\) minmax\(240px, 280px\)/)
  assert.match(styles, /\.anywhere-door-comments-embedded \.anywhere-door-comment-list \{[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.anywhere-door-media-viewer \.anywhere-door-media-frame \{[\s\S]*aspect-ratio: auto !important;/)
  assert.match(styles, /\.anywhere-door-more-posts-grid \{[\s\S]*gap: 8px;/)
})

test('Anywhere Door data paths stay local and bounded', () => {
  const feed = read('lib/social-posts.ts')
  const commentsRoute = read('app/api/anywhere-door/[postId]/comments/route.ts')
  const detail = read('lib/social-posts.ts')
  assert.match(feed, /DEFAULT_SOCIAL_PAGE_SIZE = 20/)
  assert.match(feed, /MAX_SOCIAL_PAGE_SIZE = 50/)
  assert.match(feed, /take: take \+ 1/)
  assert.match(commentsRoute, /parentId/)
  assert.match(commentsRoute, /decodeSocialCommentCursor/)
  assert.doesNotMatch(detail, /replies:\s*\{[\s\S]*include:/)
})
