import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const root = process.cwd()
const read = (path: string) => readFileSync(`${root}/${path}`, 'utf8')

test('Anywhere Door responsive contract covers required mobile and desktop viewports', () => {
  const page = read('app/anywhere-door/page.tsx')
  const detail = read('app/anywhere-door/[postId]/page.tsx')
  const detailComponent = read('components/anywhere-door/AnywhereDoorDetail.tsx')
  const morePosts = read('components/anywhere-door/AnywhereDoorMorePosts.tsx')
  const carousel = read('components/anywhere-door/MediaCarousel.tsx')
  const card = read('components/anywhere-door/AnywhereDoorPostCard.tsx')
  const comments = read('components/anywhere-door/AnywhereDoorCommentPanel.tsx')
  const requiredMobileWidths = [360, 390, 430]
  const requiredDesktopWidths = [1366, 1440, 1920]

  assert.deepEqual(requiredMobileWidths, [360, 390, 430])
  assert.deepEqual(requiredDesktopWidths, [1366, 1440, 1920])
  assert.match(page, /max-w-\[1280px\]/)
  assert.match(page, /px-3 py-4/)
  assert.match(page, /hidden lg:block/)
  assert.match(page, /lg:hidden/)
  assert.match(detail, /max-w-\[1280px\]/)
  assert.match(detail, /px-3 py-4/)
  assert.match(detailComponent, /data-anywhere-door-detail-shell/)
  assert.match(detailComponent, /lg:grid-cols-\[minmax\(0,1\.25fr\)_minmax\(320px,0\.75fr\)_280px\]/)
  assert.match(detailComponent, /lg:col-span-2/)
  assert.match(detailComponent, /<AnywhereDoorCommentPanel embedded/)
  assert.match(detailComponent, /bg-black/)
  assert.match(morePosts, /data-anywhere-door-more-posts/)
  assert.match(morePosts, /hidden min-w-0 lg:block/)
  assert.match(morePosts, /href=\{`\/anywhere-door\/\$\{post\.id\}`\}/)
  assert.match(morePosts, /object-cover/)
  assert.match(morePosts, /'▧' : '▶'/)
  assert.doesNotMatch(morePosts, />\{post\.mediaType\}<\/span>/)
  assert.match(carousel, /overflow-hidden/)
  assert.match(carousel, /bg-black/)
  assert.match(carousel, /h-full w-full object-contain/)
  assert.doesNotMatch(carousel, />\{current\.type\}<\/span>/)
  assert.match(carousel, /aspect-square/)
  assert.match(carousel, /sm:aspect-\[4\/3\]/)
  assert.match(carousel, /lg:h-full lg:aspect-auto/)
  assert.match(comments, /break-words/)
  assert.match(comments, /加载更多评论/)
  assert.match(comments, /查看更多回复/)
  assert.match(comments, /lg:overflow-y-auto/)
  assert.match(comments, /overflow-visible[^']*lg:overflow-hidden/)
  assert.match(card, /p-0 sm:p-4/)
  assert.match(card, /px-3 pb-4 pt-4/)
  assert.match(comments, /data-anywhere-door-comments=\{embedded \? 'embedded' : 'standalone'\}/)
  assert.match(detailComponent, /dark:bg-slate-900\/90/)
})

test('Anywhere Door data paths stay local and bounded', () => {
  const feed = read('lib/social-posts.ts')
  const commentsRoute = read('app/api/anywhere-door/[postId]/comments/route.ts')
  const detail = read('lib/social-posts.ts')
  assert.match(feed, /DEFAULT_SOCIAL_PAGE_SIZE = 20/)
  assert.match(feed, /MAX_SOCIAL_PAGE_SIZE = 50/)
  assert.match(feed, /take: take \+ 1/)
  assert.match(commentsRoute, /parentId/)
  assert.match(commentsRoute, /decodeSocialCommentCursor/)
  assert.doesNotMatch(detail, /replies:\s*\{[\s\S]*include:/)
})
