import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(path, 'utf8')

test('BadgeImage has separate visual layers for shine, glow and sparkle', () => {
  const component = read('components/UserDisplayName.tsx')
  const css = read('app/globals.css')
  assert.match(component, /badge-visual/)
  assert.match(component, /badge-shimmer-clip/)
  assert.match(component, /badge-shimmer-layer/)
  assert.match(component, /badgeTextEffectClass/)
  assert.match(component, /badgeTextStyle/)
  assert.match(component, /badge-visual-sparkles/)
  assert.match(component, /effectType === 'SPARKLE'/)
  assert.match(component, /effectType === 'SHINE'/)
  assert.match(css, /\.badge-effect-shine \.badge-shimmer-clip/)
  assert.match(css, /\.badge-effect-shine \.badge-shimmer-layer/)
  assert.match(css, /\.badge-effect-shine \.user-badge-image[\s\S]*animation:eason-badge-shine-fallback 4s linear infinite/)
  assert.match(css, /\.badge-effect-glow \.user-badge-image/)
  assert.match(css, /\.badge-visual-sparkles i/)
  assert.match(css, /@keyframes eason-badge-shine/)
  assert.match(css, /@keyframes eason-badge-glow/)
  assert.match(css, /@keyframes eason-badge-sparkle/)
})

test('BadgeName applies badge animationEffect without coupling it to nickname shine', () => {
  const component = read('components/UserDisplayName.tsx')
  assert.match(component, /export function BadgeName/)
  assert.match(component, /badgeNameEffectClass/)
  assert.match(component, /isBadgeNicknameShineEnabled/)
  assert.match(component, /displayBadge && showBadgeIcon/)
  assert.match(component, /<BadgeName badge=\{displayBadge\}/)
  assert.match(read('components/BadgeExhibitionHall.tsx'), /<BadgeName badge=\{badge\}/)
  assert.match(read('components/BadgeCollectionPanel.tsx'), /<BadgeName badge=\{badge\}/)
  assert.match(read('components/BadgeMiniShowcase.tsx'), /<BadgeName badge=\{item\}/)
})

test('nickname shine keeps an inherited base layer and a separate narrow color overlay', () => {
  const component = read('components/UserDisplayName.tsx')
  const css = read('app/globals.css')
  const nicknameCss = css.slice(css.indexOf('/* E院勋章'), css.indexOf('.user-display-badge {'))
  assert.match(component, /isBadgeNicknameShineEnabled/)
  assert.match(component, /getBadgeNicknameShineColor/)
  assert.match(component, /className="user-display-name-base"/)
  assert.match(component, /className="user-display-name-highlight" aria-hidden="true"/)
  assert.match(component, /nicknameShineEnabled \?/)
  assert.match(nicknameCss, /\.user-display-name-shine \{[^}]*color:inherit/)
  assert.match(nicknameCss, /\.user-display-name-base \{ color:inherit; \}/)
  assert.match(nicknameCss, /\.user-display-name-highlight \{[^}]*color:var\(--badge-shine-color/)
  assert.match(nicknameCss, /-webkit-mask-image:linear-gradient/)
  assert.match(nicknameCss, /-webkit-mask-size:260% 100%; mask-size:260% 100%/)
  assert.match(nicknameCss, /animation:eason-badge-nickname-shine 2s ease-in-out infinite normal/)
  assert.doesNotMatch(nicknameCss, /alternate(?:-reverse)?/)
  const keyframeStart = css.indexOf('@keyframes eason-badge-nickname-shine')
  const nicknameKeyframes = css.slice(keyframeStart, css.indexOf('\n', keyframeStart))
  assert.match(nicknameKeyframes, /0%[^}]*mask-position:100% 0/)
  assert.match(nicknameKeyframes, /100%[^}]*mask-position:0 0/)
  assert.doesNotMatch(nicknameKeyframes, /mask-position:0 0[^}]*mask-position:100% 0/)
  assert.doesNotMatch(component, /nicknameEffectClass|user-display-name-text-gradient/)
  assert.doesNotMatch(nicknameCss, /background-clip:text|-webkit-text-fill-color|text-shadow/)
})

test('nickname shine is omitted when disabled and reduced motion keeps only inherited text', () => {
  const component = read('components/UserDisplayName.tsx')
  const css = read('app/globals.css')
  assert.match(component, /nicknameShineEnabled \?/)
  assert.match(component, /<span className=\{`user-display-name-text \$\{nameClassName\}`\.trim\(\)\}>\{name\}<\/span>/)
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.user-display-name-highlight \{ display:none; animation:none; \}/)
  assert.doesNotMatch(css, /\.user-display-name-highlight[^}]*text-fill-color/)
})

test('badge admin exposes only nickname shine controls and themed previews', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /昵称闪光/)
  assert.match(manager, /昵称闪光颜色/)
  assert.match(manager, /不会改变昵称原本颜色/)
  assert.match(manager, /showBadgeIcon=\{false\}/)
  assert.match(manager, /浅色页面预览/)
  assert.match(manager, /深色页面预览/)
  assert.doesNotMatch(manager, /昵称效果<select|昵称颜色<input|渐变起始颜色|渐变结束颜色/)
})

test('shine uses a duplicate alpha image and a clipped scan instead of a rectangle mask', () => {
  const component = read('components/UserDisplayName.tsx')
  const css = read('app/globals.css')
  assert.match(component, /className="badge-shimmer-clip"/)
  assert.match(component, /<img src=\{badge\.imageUrl \|\| ''\} alt="" className="badge-shimmer-layer" \/>/)
  assert.match(component, /className="user-badge-image"/)
  assert.equal((component.match(/className="user-badge-image"/g) || []).length, 1)
  assert.doesNotMatch(component, /badge-shine-mask/)
  assert.match(css, /\.badge-shimmer-clip \{[\s\S]*overflow:hidden[\s\S]*opacity:0/)
  assert.match(css, /@supports \(clip-path:polygon\(0 0,100% 0,100% 100%,0 100%\)\)[\s\S]*\.badge-effect-shine \.badge-shimmer-clip \{[\s\S]*opacity:1/)
  assert.match(css, /\.badge-shimmer-layer \{[\s\S]*clip-path:polygon\([\s\S]*filter:brightness\([\s\S]*drop-shadow[\s\S]*transform:translate3d\(-140%,0,0\)/)
  assert.doesNotMatch(css, /\.badge-shimmer-layer \{[^}]*background(?:-color)?:/)
  assert.doesNotMatch(css, /\.badge-shimmer-clip \{[^}]*background(?:-color)?:/)
  assert.doesNotMatch(css, /\.badge-shimmer-clip \{[^}]*border(?:-\w+)?:/)
  assert.doesNotMatch(css, /\.badge-shimmer-clip \{[^}]*box-shadow:/)
  assert.doesNotMatch(css, /badge-shine-mask|mask-image:var\(--badge-shine-mask\)/)
  assert.match(css, /\.badge-visual \{[\s\S]*border:0[\s\S]*background:transparent[\s\S]*box-shadow:none/)
  assert.match(css, /@keyframes eason-badge-shine[\s\S]*transform:translate3d\(-140%,0,0\)/)
  assert.match(css, /@keyframes eason-badge-shine-fallback[\s\S]*filter:drop-shadow/)
  assert.match(css, /animation:eason-badge-shine 4s linear infinite; animation-play-state:running/)
  assert.match(css, /\.badge-effect-glow \.user-badge-image[\s\S]*animation:eason-badge-glow/)
  assert.match(css, /filter:drop-shadow/)
  assert.doesNotMatch(css, /@property[^}]*badge-shine/)
  assert.doesNotMatch(component, /<img[^>]+badge-visual-shine/)
})

test('interactive badge details keep an accessible rounded focus outline while profile badges stay static', () => {
  const component = read('components/UserDisplayName.tsx')
  const profileSummary = read('components/ProfileSummary.tsx')
  const profileSurface = read('components/ProfilePageSurface.tsx')
  const css = read('app/globals.css')
  assert.match(css, /\.user-display-badge-interactive:focus-visible \{[^}]*outline:2px solid/)
  assert.match(css, /\.user-display-badge-interactive:focus-visible \{[^}]*border-radius:999px/)
  assert.doesNotMatch(css, /\.user-display-badge-interactive:focus-visible \{[^}]*box-shadow/)
  assert.match(component, /badgeInteraction\?: 'interactive' \| 'static'/)
  assert.match(component, /user-display-badge-static/)
  assert.match(profileSummary, /badgeInteraction\?: 'interactive' \| 'static'/)
  assert.match(profileSurface, /badgeInteraction=\{isSelf \? 'static' : 'interactive'\}/)
  assert.match(css, /\.user-display-badge-static \{[^}]*cursor:default/)
})

test('profile UID stays static while the shared nickname overlay remains text-only', () => {
  const component = read('components/UserDisplayName.tsx')
  const profileSummary = read('components/ProfileSummary.tsx')
  const css = read('app/globals.css')
  assert.match(component, /badge-text-shine/)
  assert.doesNotMatch(profileSummary, /badgeTextEffectClass|badgeTextStyle/)
  assert.match(profileSummary, /profile-hero-identity/)
  assert.match(css, /\.user-display-name-highlight[\s\S]*animation:eason-badge-nickname-shine 2s ease-in-out infinite normal/)
  assert.match(css, /\.profile-identity-badge \{[^}]*border:0;[^}]*background:transparent;[^}]*box-shadow:none/)
  assert.match(css, /\.profile-hero-identity \{[^}]*border:0;[^}]*background:transparent;[^}]*box-shadow:none/)
  assert.match(css, /\.badge-visual \{[^}]*border:0;[^}]*background:transparent;[^}]*box-shadow:none/)
})

test('museum and mini showcase keep GLOW on the badge image instead of the shelf item', () => {
  const css = read('app/globals.css')
  assert.match(css, /\.badge-museum-item-image \.badge-visual\.badge-effect-glow \.user-badge-image,\n\.badge-mini-showcase-image \.badge-visual\.badge-effect-glow \.user-badge-image \{[\s\S]*animation:eason-badge-glow/)
  assert.doesNotMatch(css, /\.badge-museum-item[^}]*box-shadow:[^n]/)
})

test('effects keep their envelope visible, reduce motion without disappearing, and downgrade unearned museum badges', () => {
  const css = read('app/globals.css')
  assert.match(css, /\.badge-visual[\s\S]*overflow:visible/)
  assert.match(css, /\.badge-museum-cabinet \{ overflow:visible; \}/)
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.badge-effect-shine \.badge-shimmer-layer[\s\S]*animation:none/)
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.badge-effect-shine \.badge-shimmer-layer \{[^}]*opacity:0/)
  assert.match(css, /\.badge-effect-glow \.user-badge-image[\s\S]*animation:none[\s\S]*filter:drop-shadow/)
  assert.match(css, /\.badge-museum-item:not\(\.is-obtained\) \.badge-visual\.badge-effect-sparkle \.badge-visual-sparkles i[\s\S]*animation:none/)
})

test('failed images use the neutral placeholder and do not inherit a real badge effect', () => {
  const component = read('components/UserDisplayName.tsx')
  assert.match(component, /if \(!hasImage\) return <span className=\{`user-badge-placeholder/)
  assert.doesNotMatch(component, /user-badge-placeholder[^\n]*badgeEffectClass/)
})
