import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { parseBadgeDefinition } from '@/lib/badge-admin'
import { BADGE_ADMIN_RULE_TYPES, BADGE_RULE_REGISTRY, BADGE_RULE_TYPES, generateBadgeAcquisitionDescription, parseBadgeRuleInput } from '@/lib/badge-rules'

const read = (path: string) => readFileSync(path, 'utf8')
const baseBadge = { name: '自动测试勋章', code: 'auto_test_1' }

test('AUTO + registry rule + positive integer threshold is accepted', () => {
  const parsed = parseBadgeDefinition({
    ...baseBadge,
    grantType: 'AUTO',
    rule: { ruleType: 'POST_COUNT', operator: 'GTE', threshold: 100 },
  })
  assert.equal(parsed.error, undefined)
  assert.equal(parsed.rule?.ruleType, 'POST_COUNT')
  assert.equal(parsed.rule?.operator, 'GTE')
  assert.equal(parsed.rule?.threshold, 100)
})

test('AUTO without a complete rule is rejected by the shared server parser', () => {
  assert.match(parseBadgeDefinition({ ...baseBadge, grantType: 'AUTO' }).error || '', /自动授予勋章必须配置获取条件/)
  assert.match(parseBadgeDefinition({ ...baseBadge, grantType: 'AUTO', rule: { ruleType: 'POST_COUNT' } }).error || '', /阈值/)
})

test('AUTO thresholds reject zero, negative, decimal, NaN, Infinity and missing values', () => {
  for (const threshold of [0, -1, 1.5, Number.NaN, Number.POSITIVE_INFINITY, undefined]) {
    assert.match(parseBadgeRuleInput({ ruleType: 'POST_COUNT', operator: 'GTE', threshold }).error || '', /阈值/)
  }
})

test('AUTO rule threshold uses the registry maximum rather than a client-only limit', () => {
  assert.equal(parseBadgeRuleInput({ ruleType: 'POST_COUNT', operator: 'GTE', threshold: 1_000_000_000 }).error, undefined)
  assert.match(parseBadgeRuleInput({ ruleType: 'POST_COUNT', operator: 'GTE', threshold: 1_000_000_001 }).error || '', /阈值/)
})

test('MANUAL and EVENT accept descriptive text without BadgeRule', () => {
  assert.equal(parseBadgeDefinition({ ...baseBadge, grantType: 'MANUAL', acquisitionDescription: '管理员授予' }).error, undefined)
  assert.equal(parseBadgeDefinition({ ...baseBadge, grantType: 'EVENT', acquisitionDescription: '生日事件' }).error, undefined)
})

test('MANUAL and EVENT cannot carry a structured rule', () => {
  for (const grantType of ['MANUAL', 'EVENT']) {
    assert.equal(parseBadgeDefinition({ grantType, rule: { ruleType: 'POST_COUNT', threshold: 1 } }, true).error, '手动或事件勋章不能配置自动获取规则')
  }
})

test('registry is the only rule catalog used by the admin surface', () => {
  assert.equal(BADGE_RULE_TYPES.length, 12)
  assert.ok(BADGE_RULE_TYPES.every((ruleType) => BADGE_RULE_REGISTRY[ruleType].label && BADGE_RULE_REGISTRY[ruleType].dataDescription))
  assert.equal(BADGE_ADMIN_RULE_TYPES.length, 12)
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /BADGE_ADMIN_RULE_TYPES\.map/)
  assert.match(manager, /BADGE_RULE_TYPE_DESCRIPTIONS\[draft\.ruleType\]/)
})

test('operator UI exposes only the supported GTE presentation', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /比较方式/)
  assert.match(manager, /达到（≥）/)
  assert.doesNotMatch(manager, /<select[^>]+operator/)
})

test('default acquisition copy is generated by the registry and does not define the rule', () => {
  assert.equal(generateBadgeAcquisitionDescription('CHECKIN_TOTAL_DAYS', 100), '累计挂号 100 天后获得')
  assert.equal(parseBadgeRuleInput({ ruleType: 'CHECKIN_TOTAL_DAYS', operator: 'GTE', threshold: 100 }).rule?.threshold, 100)
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /generateBadgeAcquisitionDescription/)
  assert.match(manager, /仅用于前台展示，不参与自动授予判断/)
})

test('custom copy tracking is limited to structured AUTO badges', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /draft\.grantType === 'AUTO' && !draft\.legacyAuto/)
  assert.match(manager, /acquisitionDescriptionCustomized: false/)
  assert.match(manager, /恢复默认文案/)
})

test('editing a legacy AUTO badge keeps the historical flow visible', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  const route = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(manager, /旧业务自动徽章/)
  assert.match(manager, /启用结构化规则/)
  assert.match(route, /keepsLegacyAutoFlow/)
})

test('missing stored default copy is regenerated when a structured AUTO badge is opened', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /followsGeneratedDescription/)
  assert.match(manager, /generateBadgeAcquisitionDescription\(rule!\.ruleType, rule!\.threshold\)/)
})

test('explicit reset-to-default is enforced server-side', () => {
  const createRoute = read('app/api/admin/badges/route.ts')
  const updateRoute = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(createRoute, /body\.acquisitionDescriptionCustomized === false/)
  assert.match(updateRoute, /explicitlyResetToDefault/)
  assert.match(updateRoute, /data\.acquisitionDescriptionCustomized = false/)
})

test('Badge and BadgeRule mutations are kept in the same transaction', () => {
  const createRoute = read('app/api/admin/badges/route.ts')
  const updateRoute = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(createRoute, /prisma\.\$transaction\(async \(tx\)/)
  assert.match(createRoute, /tx\.badgeRule\.create/)
  assert.match(updateRoute, /prisma\.\$transaction\(async \(tx\)/)
  assert.match(updateRoute, /tx\.badgeRule\.upsert/)
})

test('switching away from AUTO removes the structured rule without revoking history', () => {
  const route = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(route, /const effectiveRule = nextGrantType === 'AUTO'/)
  assert.match(route, /tx\.badgeRule\.delete\(\{ where: \{ badgeId \} \}\)/)
  assert.doesNotMatch(route, /revokeBadge\(/)
})

test('switching MANUAL or EVENT to AUTO still requires a new complete rule', () => {
  const route = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(route, /nextGrantType === 'AUTO' && !effectiveRule && !keepsLegacyAutoFlow/)
  assert.match(route, /自动授予勋章必须配置获取条件/)
})

test('direct PATCH cannot attach a structured rule to MANUAL or EVENT', () => {
  const route = read('app/api/admin/badges/[badgeId]/route.ts')
  assert.match(route, /if \(parsed\.rule && nextGrantType !== 'AUTO'\)/)
  assert.match(route, /手动或事件勋章不能配置自动获取规则/)
})

test('rule preview re-checks AUTO and enabled state server-side', () => {
  const engine = read('lib/badge-rule-engine.ts')
  assert.match(engine, /if \(badge\.grantType !== 'AUTO'\)/)
  assert.match(engine, /if \(!badge\.isEnabled \|\| !badge\.isActive\)/)
})

test('validation errors reopen the relevant collapsed form section', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /setFormSections\(\(current\) => \(\{ \.\.\.current, rules: true \}\)\)/)
  assert.match(manager, /open=\{formSections\.display\}/)
})

test('preview is read-only, permission protected and available from the rule area after save', () => {
  const route = read('app/api/admin/badges/[badgeId]/preview/route.ts')
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(route, /requireAdmin\('achievement_manage'\)/)
  assert.match(manager, /预览已保存规则/)
  assert.match(manager, /预览只读/)
})

test('backfill requires confirmation, saved badge state and limited-badge protection', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  const engine = read('lib/badge-rule-engine.ts')
  assert.match(manager, /window\.confirm\(`将为当前符合/)
  assert.match(manager, /请先保存勋章，再执行自动补发/)
  assert.match(manager, /限定勋章不可自动补发/)
  assert.match(engine, /限定勋章没有可靠的历史达标时间，不能使用自动历史补发/)
})

test('Tier and availability controls are optional and clear fields when disabled', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /tierEnabled/)
  assert.match(manager, /limitedEnabled/)
  assert.match(manager, /tierGroupCode: event\.target\.checked \? .* : null/)
  assert.match(manager, /availableUntil: event\.target\.checked \? draft\.availableUntil : null/)
})

test('server permissions remain on every Badge mutation path', () => {
  for (const path of ['app/api/admin/badges/route.ts', 'app/api/admin/badges/[badgeId]/route.ts', 'app/api/admin/badges/[badgeId]/preview/route.ts', 'app/api/admin/badges/[badgeId]/backfill/route.ts']) {
    assert.match(read(path), /requireAdmin\('achievement_manage'\)/)
  }
})
