import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(path, 'utf8')

test('管理员收回预览入口与 API 只读且受成就管理权限保护', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  const route = read('app/api/admin/badges/[badgeId]/revoke-preview/route.ts')
  assert.match(manager, /收回预览/)
  assert.match(manager, /isRevokePreviewBadge/)
  assert.match(manager, /SafeAvatar/)
  assert.match(manager, /PENDING_REVOKE/)
  assert.match(manager, /STILL_ELIGIBLE/)
  assert.match(manager, /RETAINED_INELIGIBLE/)
  assert.match(route, /requireAdmin\('achievement_manage'\)/)
  assert.match(route, /previewBadgeRuleRevocations\(badgeId/)
  assert.match(route, /Cache-Control.*no-store/)
  assert.doesNotMatch(route, /prisma\./)
  assert.doesNotMatch(route, /revokeBadge|revokeBadgeAcquisitionSource|UserBadge|AdminActionLog/)
})

test('收回执行必须二次确认、记录审计并返回执行明细', () => {
  const route = read('app/api/admin/badges/[badgeId]/revoke-preview/execute/route.ts')
  assert.match(route, /requireAdmin\('achievement_manage'\)/)
  assert.match(route, /confirmed.*!== true/)
  assert.match(route, /executeBadgeRuleRevocations\(badgeId/)
  assert.match(route, /prisma\.\$transaction\(async \(tx\)/)
  assert.match(route, /writeBadgeAdminAction\(tx/)
  assert.match(route, /ADMIN_REVOKE_PREVIEW_EXECUTION/)
  assert.match(route, /preview:/)
  assert.match(route, /actual:/)
  assert.match(route, /skipped:/)
  assert.match(route, /executedAt:/)
  assert.match(route, /auditRecorded: true/)
  assert.doesNotMatch(route, /tx\.userBadge\.(update|delete|updateMany|deleteMany)/)
})

test('预览与执行共享同一个实时资格与保留策略决策，并按来源调用正式收回原语', () => {
  const engine = read('lib/badge-retention.ts')
  const previewStart = engine.indexOf('export async function previewBadgeRuleRevocations')
  const executeStart = engine.indexOf('export async function executeBadgeRuleRevocations')
  assert.ok(previewStart >= 0 && executeStart > previewStart)
  const preview = engine.slice(previewStart, executeStart)
  const execution = engine.slice(executeStart)
  assert.match(preview, /evaluateOwnerForRevocation\(owner, contexts, now\)/)
  assert.match(engine, /const satisfied = await isBadgeRuleSatisfied\(owner\.user\.id, context\.rule, now\)/)
  assert.match(engine, /retentionPolicy: resolveBadgeRetentionPolicy\(rule\)/)
  assert.doesNotMatch(preview, /revokeBadgeAcquisitionSource|prisma\.\$transaction|\.update\(/)
  assert.match(execution, /previewBadgeRuleRevocations\(badgeId/)
  assert.match(execution, /loadRevokeRuleContext\(badgeId\)/)
  assert.match(execution, /loadActiveBadgeOwners\(badgeId, contexts, now\)/)
  assert.match(execution, /evaluateOwnerForRevocation\(owner, contexts, now\)/)
  assert.match(execution, /revokeBadgeAcquisitionSource\(/)
  assert.match(execution, /sourceType: source\.sourceType/)
  assert.match(execution, /sourceId: source\.sourceId \|\| ''/)
})

test('预览来源精确绑定规则或活动，生日兼容来源覆盖旧生日勋章', () => {
  const engine = read('lib/badge-retention.ts')
  assert.match(engine, /sourceType: governedSourceTypes\(rule\.ruleType\)\[0\], sourceId: rule\.id/)
  assert.match(engine, /sourceType: 'ACTIVITY_PARTICIPATION', sourceId: activityId/)
  assert.match(engine, /sourceType: 'AUTO', sourceId: BIRTHDAY_BADGE_SLUG/)
  assert.match(engine, /sourceType: 'LEGACY', sourceId: null/)
  assert.match(engine, /resolveZodiac/)
  assert.match(engine, /当前生日并非今天/)
})

test('前台确认执行会把搜索范围传给服务，并显示收回/跳过/失败汇总', () => {
  const manager = read('app/admin/badges/BadgeAdminManager.tsx')
  assert.match(manager, /window\.confirm\(`确认批量收回/)
  assert.match(manager, /confirmed: true/)
  assert.match(manager, /query: revokePreviewQuery\.trim\(\)/)
  assert.match(manager, /实际收回/)
  assert.match(manager, /跳过原因/)
  assert.match(manager, /失败摘要/)
  assert.match(manager, /当前生日/)
  assert.match(manager, /获得时间/)
  assert.match(manager, /保留策略/)
})
