import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(path, 'utf8')

test('推荐页桌面刷新按钮复用现有 loadPage，移动端隐藏且避免重复请求', () => {
  const home = read('components/ForumHome.tsx')
  const discovery = read('components/ForumDiscoveryHome.tsx')
  const css = read('app/globals.css')

  assert.match(home, /showDesktopRefresh=\{!previewMode\}/)
  assert.match(discovery, /showDesktopRefresh && mode === 'recommend'/)
  assert.match(discovery, /onClick=\{\(\) => void refresh\(true\)\}/)
  assert.match(discovery, /disabled=\{isRefreshing\}/)
  assert.match(discovery, /if \(refreshingRef\.current\) return/)
  assert.match(discovery, /await loadPage\(true, true\)/)
  assert.doesNotMatch(discovery, /window\.location\.reload|router\.refresh\(\)/)
  assert.match(css, /@media \(max-width:767px\)[\s\S]*\.forum-discovery-refresh-button \{ display:none; \}/)
  assert.match(css, /\.forum-discovery-refresh-button\.is-refreshing span \{ animation:forum-discovery-refresh-spin/)
})

test('帖子多图页面和查看器共用 3 秒自动轮播，交互只临时延迟且关闭后清理', () => {
  const viewer = read('components/ImageViewer.tsx')
  const carousel = read('components/PostMediaCarousel.tsx')
  const postPage = read('app/posts/[postId]/page.tsx')
  const detailController = read('components/ForumDiscoveryDetailController.tsx')

  assert.match(viewer, /IMAGE_VIEWER_AUTO_PLAY_INTERVAL_MS = 3_000/)
  assert.match(viewer, /autoPlay && viewerItems\.length > 1/)
  assert.match(viewer, /window\.setTimeout\(/)
  assert.match(viewer, /\}, IMAGE_VIEWER_AUTO_PLAY_INTERVAL_MS\)/)
  assert.match(viewer, /\(safeCurrentIndex \+ 1\) % viewerItems\.length/)
  assert.match(viewer, /clearAutoPlayTimeout\(\)/)
  assert.match(viewer, /useEffect\(\(\) => \(\) => clearAutoPlayTimeout\(\)/)
  assert.match(viewer, /const beginInteraction = useCallback/)
  assert.match(viewer, /const endInteraction = useCallback/)
  assert.match(viewer, /onPointerDown[\s\S]*beginInteraction\(\)/)
  assert.match(viewer, /onPointerMove[\s\S]*beginInteraction\(\)/)
  assert.match(viewer, /onWheel[\s\S]*beginInteraction\(\)[\s\S]*endInteraction\(\)/)
  assert.doesNotMatch(viewer, /hasUserInteracted|pauseAutoPlay|open && zoom !== 1/)
  assert.match(viewer, /document\.visibilityState === 'visible'/)
  assert.match(viewer, /onOpenChange\?\.\(true\)/)
  assert.match(viewer, /onOpenChange\?\.\(false\)/)
  assert.match(viewer, /onIndexChange\?\.\(nextIndex\)/)
  assert.match(viewer, /goTo\(safeCurrentIndex - 1\)/)
  assert.match(carousel, /gallery=\{viewerGallery\}/)
  assert.match(carousel, /autoPlay=\{viewerGallery\.length > 1\}/)
  assert.match(carousel, /viewerGallery = items[\s\S]*filter\(\(item\) => !item\.broken && !failedImageIds\.has\(item\.id\)\)/)
  assert.match(carousel, /pageAutoPlayTimeoutRef/)
  assert.match(carousel, /IMAGE_VIEWER_AUTO_PLAY_INTERVAL_MS/)
  assert.match(carousel, /isViewerOpen/)
  assert.match(carousel, /onOpenChange=\{handleViewerOpenChange\}/)
  assert.match(carousel, /onIndexChange=\{handleViewerIndexChange\}/)
  assert.match(postPage, /where: \{ type: 'IMAGE' as const \}/)
  assert.match(postPage, /hasReplyTarget=\{Boolean\(focusId\)\}/)
  assert.match(detailController, /if \(hasReplyTarget \|\| window\.location\.hash\) return/)
  assert.match(detailController, /window\.scrollTo\(\{ left: 0, top: 0, behavior: 'auto' \}\)/)
})

test('帖子详情顶栏的分享按钮在窄屏仍保持横向且不挤压标题', () => {
  const topbar = read('components/ForumDiscoveryDetailTopbar.tsx')
  const css = read('app/globals.css')
  assert.match(topbar, /triggerClassName="forum-discovery-detail-share shrink-0 whitespace-nowrap"/)
  assert.match(css, /\.forum-discovery-detail-share \{ min-width:48px; padding-inline:4px; font-size:22px; white-space:nowrap; \}/)
  assert.match(css, /\.forum-discovery-detail-author \{ display:flex; min-width:0; flex:1;/)
  assert.match(css, /\.forum-discovery-detail-post-actions \{ display:flex; min-width:0; flex:none;/)
  assert.doesNotMatch(css, /\.forum-discovery-detail-share \{[^}]*width:32px/)
})

test('帖子详情桌面端只在正文卡片右上角显示分享，不渲染额外顶部工具栏', () => {
  const detail = read('app/posts/[postId]/page.tsx')
  const css = read('app/globals.css')

  assert.equal((detail.match(/<ShareButton/g) || []).length, 1)
  assert.match(detail, /<article className="post-detail-article border[^>]*>/)
  assert.match(detail, /post-detail-card-header[\s\S]*post-detail-desktop-share[\s\S]*<ShareButton/)
  assert.match(css, /\.post-detail-desktop-share \{ display:none; flex:none; \}/)
  assert.match(css, /@media \(min-width:768px\)[\s\S]*\.post-detail-desktop-share \{ display:block; \}/)
  assert.doesNotMatch(css, /\.forum-discovery-detail-topbar \{ display:flex; width:100%;/)
  assert.match(css, /\.forum-discovery-detail-topbar,[\s\S]*\.post-reply-bottom-sheet \{ display:none; \}/)
})
