import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { parseBadgeDefinition } from '@/lib/badge-admin'
import { SALON_BADGE_CLASSIFICATION } from '@/lib/salon-badges'

const read = (path: string) => readFileSync(path, 'utf8')

test('沙龙详情编辑入口按作者或沙龙管理权限显示，API 仍服务端复核', () => {
  const detail = read('components/salon/SalonDetail.tsx')
  const page = read('app/salon/[postId]/page.tsx')
  const route = read('app/api/salon/posts/[postId]/route.ts')
  assert.match(detail, /currentUserId === post\.author\.id \|\| canModerate \? <Link href=\{editHref\}/)
  assert.match(page, /hasAdminPermission\(user, 'post_manage'\)/)
  assert.match(route, /const isOwner = current\.userId === guard\.user\.id/)
  assert.match(route, /if \(!isOwner && !canModerate\) return .*status: 403/)
})

test('作者编辑进入待审核，管理员编辑直接通过并记录统一审计', () => {
  const route = read('app/api/salon/posts/[postId]/route.ts')
  const audit = read('lib/admin-audit.ts')
  assert.match(route, /status: 'PENDING'/)
  assert.match(route, /status: 'APPROVED'/)
  assert.match(route, /operation: 'ADMIN_EDIT'/)
  assert.match(route, /createSalonReviewNotifications\(\{[\s\S]*reviewKind: 'EDIT'/)
  assert.match(audit, /SALON_POST_ADMIN_EDIT: 'SALON_POST_ADMIN_EDIT'/)
  assert.match(route, /SALON_POST_ADMIN_EDIT/)
})

test('编辑请求携带 baseUpdatedAt 并在行锁内拒绝并发旧版本覆盖', () => {
  const form = read('components/salon/SalonEditForm.tsx')
  const route = read('app/api/salon/posts/[postId]/route.ts')
  const shared = read('lib/salon-shared.ts')
  const service = read('lib/salon.ts')
  assert.match(form, /baseUpdatedAt: post\.updatedAt/)
  assert.match(form, /router\.replace\(detailHref\)/)
  assert.match(route, /FOR UPDATE/)
  assert.match(route, /SALON_EDIT_CONFLICT/)
  assert.match(shared, /updatedAt: string/)
  assert.match(service, /updatedAt: row\.updatedAt\.toISOString\(\)/)
})

test('统一审核中心标识沙龙编辑类型并复用现有通过/拒绝链路', () => {
  const api = read('app/api/admin/review/route.ts')
  const card = read('app/admin/review/ReviewCenter.tsx')
  const notifications = read('lib/salon-review-notifications.ts')
  assert.match(api, /getSalonEditReviewPostIds\(rows\.map\(\(row\) => row\.id\)\)/)
  assert.match(api, /reviewKind: editPostIds\.has\(row\.id\) \? 'EDIT' : 'CREATE'/)
  assert.doesNotMatch(api, /row\.updatedAt\.getTime\(\) > row\.createdAt\.getTime\(\)/)
  assert.match(card, /类型：\{item\.reviewKind === 'EDIT' \? '编辑' : '投稿'\}/)
  assert.match(notifications, /SALON_EDIT_REVIEW_NOTIFICATION_TITLE/)
  assert.match(notifications, /startsWith: salonEditReviewNotificationKeyPrefix\(postId\)/)
})

test('沙龙勋章目录只使用显式配置，后台可维护并复用统一发放服务', () => {
  const schema = read('prisma/schema.prisma')
  const migration = read('prisma/migrations/20260914100000_add_salon_badge_assignable/migration.sql')
  const catalog = read('lib/salon-badges.ts')
  const route = read('app/api/salon/posts/[postId]/badges/route.ts')
  const grantAdapter = read('lib/salon-badge-grant.ts')
  const ui = read('components/salon/SalonBadgeGrant.tsx')
  const admin = read('app/admin/badges/BadgeAdminManager.tsx')
  const service = read('lib/badge-service.ts')
  assert.equal(SALON_BADGE_CLASSIFICATION.available, true)
  assert.equal(SALON_BADGE_CLASSIFICATION.field, 'Badge.salonAssignable')
  assert.match(schema, /salonAssignable\s+Boolean\s+@default\(false\)/)
  assert.match(migration, /ADD COLUMN `salonAssignable` BOOLEAN NOT NULL DEFAULT false/)
  assert.match(catalog, /salonAssignable: true/)
  assert.match(catalog, /currentUserBadgeWhere\(now\)/)
  assert.match(route, /listSalonAssignableBadges\(/)
  assert.match(route, /classificationField: SALON_BADGE_CLASSIFICATION\.field/)
  assert.match(route, /requireAdmin\('achievement_manage'\)/)
  assert.doesNotMatch(route, /isAdmin\s*===\s*true/)
  assert.doesNotMatch(route, /SALON_BADGE_CLASSIFICATION_UNAVAILABLE/)
  assert.doesNotMatch(catalog, /name\.toLowerCase\(\).*沙龙|includes\(['"]沙龙/)
  assert.match(grantAdapter, /grantBadge\(/)
  assert.match(grantAdapter, /sourceType: 'SALON_ADMIN_GRANT'/)
  assert.match(grantAdapter, /grantKey: `salon-admin:/)
  assert.match(grantAdapter, /requireSalonAssignable: true/)
  assert.match(grantAdapter, /rejectIfAlreadyOwned: true/)
  assert.match(service, /BADGE_ALREADY_OWNED/)
  assert.match(service, /if \(input\.rejectIfAlreadyOwned\)/)
  assert.match(ui, /派发对象：\{author\.nickname\}/)
  assert.match(ui, /可派发勋章/)
  assert.match(ui, /已拥有/)
  assert.match(ui, /acquisitionDescription/)
  assert.doesNotMatch(ui, /搜索用户|输入 UID|选择用户/)
  assert.match(admin, /draft\.salonAssignable/)
})

test('后台勋章配置显式校验沙龙派发开关，默认关闭且支持局部更新', () => {
  const created = parseBadgeDefinition({ name: '沙龙测试勋章', salonAssignable: true })
  assert.equal(created.data?.salonAssignable, true)
  const defaulted = parseBadgeDefinition({ name: '普通测试勋章' })
  assert.equal(defaulted.data?.salonAssignable, false)
  const updated = parseBadgeDefinition({ salonAssignable: true }, true)
  assert.equal(updated.data?.salonAssignable, true)
  const invalid = parseBadgeDefinition({ salonAssignable: 'true' }, true)
  assert.equal(invalid.error, '沙龙派发开关无效')
})

test('沙龙派发列表区分配置为空与搜索无匹配，并报告迁移失配', () => {
  const ui = read('components/salon/SalonBadgeGrant.tsx')
  const route = read('app/api/salon/posts/[postId]/badges/route.ts')

  assert.match(ui, /没有找到匹配的勋章/)
  assert.match(ui, /暂无可派发的沙龙勋章/)
  assert.match(ui, /允许在沙龙派发/)
  assert.doesNotMatch(ui, /没有符合条件的沙龙勋章/)
  assert.match(route, /DATABASE_MIGRATION_OUT_OF_SYNC/)
  assert.match(route, /P2022/)
})
