import type {
  LayoutSpacing,
  LayoutWidth,
  PageLayoutConfig,
  PageLayoutModuleConfig,
  PageLayoutModuleDefinition,
  PageLayoutPageKey,
} from '@/lib/page-layout/types'
import { pageLayoutPageKeys } from '@/lib/page-layout/types'

const allWidths = ['full', 'wide', 'medium', 'narrow', 'half', 'third'] as const satisfies readonly LayoutWidth[]
const contentWidths = ['wide', 'medium', 'narrow'] as const satisfies readonly LayoutWidth[]
const cardWidths = ['full', 'wide', 'medium', 'half', 'third'] as const satisfies readonly LayoutWidth[]
const allSpacing = ['none', 'xs', 'sm', 'md', 'lg', 'xl'] as const satisfies readonly LayoutSpacing[]

export const pageLayoutPages: Record<PageLayoutPageKey, { name: string; description: string }> = {
  home: { name: '首页', description: '前台首页模块编排' },
  checkin: { name: '每日挂号', description: '每日挂号页面模块编排' },
  'admin-home': { name: '管理后台首页', description: '后台首页模块编排' },
}

export const pageLayoutRegistry: readonly PageLayoutModuleDefinition[] = [
  {
    key: 'home.hero',
    page: 'home',
    name: '首页主视觉',
    description: '首页轮播与主行动入口',
    defaultOrder: 10,
    defaultVisible: true,
    defaultWidth: 'full',
    defaultGapTop: 'sm',
    defaultGapBottom: 'md',
    allowedWidths: ['full', 'wide'],
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
    required: true,
  },
  {
    key: 'home.announcement',
    page: 'home',
    name: '首页公告',
    description: '轻量公告提示',
    defaultOrder: 20,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: false,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.checkinSummary',
    page: 'home',
    name: '快捷入口',
    description: '挂号、广场、音乐快捷入口',
    defaultOrder: 30,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'md',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: false,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.featuredPosts',
    page: 'home',
    name: '精选帖子',
    description: '首页精选帖子列表',
    defaultOrder: 40,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'md',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
    required: true,
  },
  {
    key: 'home.dailyMessages',
    page: 'home',
    name: 'E友留言',
    description: '每日留言精选',
    defaultOrder: 50,
    defaultVisible: true,
    defaultWidth: 'half',
    defaultMobileWidth: 'full',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: cardWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.music',
    page: 'home',
    name: 'EasMusic',
    description: '音乐推荐入口',
    defaultOrder: 60,
    defaultVisible: true,
    defaultWidth: 'half',
    defaultMobileWidth: 'full',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: cardWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.culture',
    page: 'home',
    name: '活动与文化',
    description: '活动、文化内容入口',
    defaultOrder: 70,
    defaultVisible: true,
    defaultWidth: 'half',
    defaultMobileWidth: 'full',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: cardWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.latestPosts',
    page: 'home',
    name: '最新动态',
    description: '预留的首页动态模块',
    defaultOrder: 80,
    defaultVisible: false,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'home.footer',
    page: 'home',
    name: '页脚',
    description: '首页页脚文案',
    defaultOrder: 90,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'md',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'checkin.header',
    page: 'checkin',
    name: '挂号页头',
    description: '每日挂号标题、说明与北京时间',
    defaultOrder: 10,
    defaultVisible: true,
    defaultWidth: 'medium',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: allWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'checkin.stats',
    page: 'checkin',
    name: '挂号统计',
    description: '今日挂号、连续天数等统计',
    defaultOrder: 20,
    defaultVisible: true,
    defaultWidth: 'medium',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: allWidths,
    allowedSpacing: allSpacing,
    supportsTitle: false,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'checkin.formOrMood',
    page: 'checkin',
    name: '今日挂号',
    description: '签到按钮与今日心情',
    defaultOrder: 30,
    defaultVisible: true,
    defaultWidth: 'medium',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: allWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
    required: true,
  },
  {
    key: 'checkin.messages',
    page: 'checkin',
    name: 'E友留言',
    description: '每日留言列表',
    defaultOrder: 40,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: allWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
    required: true,
  },
  {
    key: 'admin.header',
    page: 'admin-home',
    name: '后台页头',
    description: '管理后台欢迎与说明',
    defaultOrder: 10,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
    required: true,
  },
  {
    key: 'admin.registrationStatus',
    page: 'admin-home',
    name: '注册状态',
    description: '注册模式与环境状态',
    defaultOrder: 20,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'admin.stats',
    page: 'admin-home',
    name: '后台数据',
    description: '后台核心统计卡片',
    defaultOrder: 30,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: false,
    supportsSubtitle: false,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'admin.modules',
    page: 'admin-home',
    name: '后台模块',
    description: '后台管理入口列表',
    defaultOrder: 40,
    defaultVisible: true,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
  {
    key: 'admin.deploymentStatus',
    page: 'admin-home',
    name: '部署状态',
    description: '预留的部署状态提示模块',
    defaultOrder: 50,
    defaultVisible: false,
    defaultWidth: 'wide',
    defaultGapTop: 'sm',
    defaultGapBottom: 'sm',
    allowedWidths: contentWidths,
    allowedSpacing: allSpacing,
    supportsTitle: true,
    supportsSubtitle: true,
    supportsDesktop: true,
    supportsMobile: true,
  },
]

export function isPageLayoutPageKey(value: unknown): value is PageLayoutPageKey {
  return typeof value === 'string' && pageLayoutPageKeys.includes(value as PageLayoutPageKey)
}

export function getPageLayoutRegistry(pageKey: PageLayoutPageKey) {
  return pageLayoutRegistry.filter((item) => item.page === pageKey)
}

export function getPageLayoutModule(pageKey: PageLayoutPageKey, key: string) {
  return getPageLayoutRegistry(pageKey).find((item) => item.key === key) || null
}

function defaultModuleConfig(module: PageLayoutModuleDefinition, device: 'desktop' | 'mobile'): PageLayoutModuleConfig {
  return {
    key: module.key,
    order: module.defaultOrder,
    visible: module.defaultVisible,
    width: device === 'mobile' ? module.defaultMobileWidth || 'full' : module.defaultWidth,
    gapTop: device === 'mobile' && module.defaultGapTop === 'md' ? 'sm' : module.defaultGapTop,
    gapBottom: device === 'mobile' && module.defaultGapBottom === 'md' ? 'sm' : module.defaultGapBottom,
    alignment: 'left',
    density: 'normal',
    title: null,
    subtitle: null,
  }
}

export function getDefaultPageLayoutConfig(pageKey: PageLayoutPageKey): PageLayoutConfig {
  const modules = getPageLayoutRegistry(pageKey)
  return {
    desktop: modules.filter((item) => item.supportsDesktop).map((item) => defaultModuleConfig(item, 'desktop')),
    mobile: modules.filter((item) => item.supportsMobile).map((item) => defaultModuleConfig(item, 'mobile')),
  }
}
