ALTER TABLE `SalonPost`
  MODIFY `category` ENUM('CONCERT', 'MOBILE_WALLPAPER', 'DESKTOP_WALLPAPER', 'TIME_TRAVEL') NOT NULL,
  MODIFY `concertId` VARCHAR(191) NULL;

ALTER TABLE `SalonPostMedia`
  MODIFY `originalUrl` TEXT NULL;
