ALTER TABLE `CheckIn`
  ADD COLUMN `moodType` VARCHAR(16) NULL,
  ADD COLUMN `moodEmoji` VARCHAR(32) NULL,
  ADD COLUMN `moodText` VARCHAR(191) NULL;

ALTER TABLE `DailyMessage`
  ADD COLUMN `moodType` VARCHAR(16) NULL,
  ADD COLUMN `moodEmoji` VARCHAR(32) NULL,
  ADD COLUMN `moodText` VARCHAR(191) NULL;

ALTER TABLE `FriendActivity`
  ADD COLUMN `moodType` VARCHAR(16) NULL,
  ADD COLUMN `moodEmoji` VARCHAR(32) NULL,
  ADD COLUMN `moodText` VARCHAR(191) NULL;
