import Link from 'next/link'
import { requireAdminPage } from '@/components/AdminAccess'
import { getBadgeAnalytics, type BadgeAnalyticsRange } from '@/lib/badge-phase5'

export const dynamic = 'force-dynamic'
export const metadata = { title: '勋章数据看板 | 私家E院' }

export default async function BadgeAnalyticsPage({ searchParams }: { searchParams?: Promise<{ range?: string; page?: string }> }) {
  await requireAdminPage('/admin/badges/analytics', 'achievement_manage')
  const params = await searchParams
  const range: BadgeAnalyticsRange = params?.range === 'all' ? 'all' : '30d'
  const page = Math.max(1, Number.parseInt(params?.page || '1', 10) || 1)
  const data = await getBadgeAnalytics(range, page, 20)
  const cards = [['勋章总数', data.summary.totalBadges], ['自动勋章', data.summary.autoBadges], ['限定勋章', data.summary.limitedBadges], ['绝版勋章', data.summary.endedBadges], ['总发放次数', data.summary.totalGrants], [range === '30d' ? '近30天新增' : '范围内新增', data.summary.rangeGrants], ['平均收藏数', data.summary.averageOwned.toFixed(1)]] as const
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-5 sm:py-8">
    <header className="rounded-[28px] border border-sky-100 bg-white p-6"><p className="text-xs font-black tracking-[0.18em] text-sky-700">BADGE ANALYTICS</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black text-brand-950">勋章数据看板</h1><p className="mt-2 text-sm font-bold text-slate-500">观察规则难度、获得趋势和追踪热度；看板只读，不会自动补发或修改规则。</p></div><Link href="/admin/badges" className="rounded-full bg-brand-950 px-4 py-2 text-xs font-black text-white">返回勋章管理</Link></div></header>
    <nav className="flex gap-2"><Link href="?range=30d" className={`rounded-full px-4 py-2 text-xs font-black ${range === '30d' ? 'bg-brand-950 text-white' : 'bg-sky-50 text-brand-700'}`}>近30天</Link><Link href="?range=all" className={`rounded-full px-4 py-2 text-xs font-black ${range === 'all' ? 'bg-brand-950 text-white' : 'bg-sky-50 text-brand-700'}`}>全部</Link></nav>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{cards.map(([label, value]) => <article key={label} className="rounded-2xl border border-sky-100 bg-white p-4"><span className="text-xs font-bold text-slate-500">{label}</span><strong className="mt-1 block text-xl font-black text-brand-950">{typeof value === 'number' ? value.toLocaleString('zh-CN') : value}</strong></article>)}</section>
    <section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="overflow-x-auto rounded-[24px] border border-sky-100 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-sky-50 text-brand-950"><tr><th className="p-3">勋章</th><th className="p-3">规则</th><th className="p-3">达标</th><th className="p-3">拥有</th><th className="p-3">待补发</th><th className="p-3">获得率</th><th className="p-3">实际难度</th><th className="p-3">追踪</th></tr></thead><tbody>{data.badges.map((badge) => <tr key={badge.id} className="border-t border-sky-50"><td className="p-3 font-black text-brand-950">{badge.name}</td><td className="p-3 text-slate-500">{badge.BadgeRule ? `${badge.BadgeRule.ruleType}${badge.BadgeRule.threshold === null ? '' : ` ≥ ${badge.BadgeRule.threshold}`}` : badge.grantType}</td><td className="p-3">{badge.eligibleCount ?? '-'}</td><td className="p-3">{badge.ownerCount}</td><td className="p-3">{badge.pendingCount ?? '-'}</td><td className="p-3">{badge.ownershipRate}</td><td className="p-3"><span className="rounded-full bg-sky-50 px-2 py-1 font-black text-brand-700">{badge.difficulty}</span></td><td className="p-3">{badge._count.UserBadgeTracking}</td></tr>)}</tbody></table></div><aside className="rounded-[24px] border border-sky-100 bg-white p-5"><h2 className="text-lg font-black text-brand-950">追踪热门</h2><div className="mt-3 space-y-3">{data.trackingPopular.length ? data.trackingPopular.map((item, index) => <div key={item.badgeId} className="flex justify-between gap-3 text-sm"><span className="font-bold text-slate-600">{index + 1}. {item.name}</span><strong className="text-brand-700">{item.count}</strong></div>) : <p className="text-sm font-bold text-slate-500">暂无追踪数据</p>}</div></aside></section>
    {range === '30d' ? <section className="rounded-[24px] border border-sky-100 bg-white p-5"><h2 className="text-lg font-black text-brand-950">近30天发放趋势</h2><div className="mt-3 flex min-h-24 items-end gap-1 overflow-x-auto">{data.trend.map((item) => <div key={item.day} title={`${item.day}: ${item.count}`} className="min-w-2 flex-1 rounded-t bg-sky-300" style={{ height: `${Math.max(4, Math.min(100, item.count))}px` }} />)}</div></section> : null}
    <section className="rounded-[24px] border border-sky-100 bg-white p-5"><h2 className="text-lg font-black text-brand-950">系列完成情况</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.series.map((series) => <article key={series.id} className="rounded-2xl bg-sky-50/60 p-4"><div className="flex justify-between gap-3"><strong className="text-sm font-black text-brand-950">{series.name}</strong><span className="text-xs font-black text-brand-700">{series.completionRate < 0.1 && series.completionRate > 0 ? '<0.1%' : `${series.completionRate.toFixed(1)}%`}</span></div><p className="mt-2 text-xs font-bold text-slate-500">{series.badgeCount} 枚计入完成 · {series.completedUsers} 人完成</p>{series.reward ? <p className="mt-1 text-xs font-bold text-amber-700">奖励：{series.reward.name}</p> : null}</article>)}</div></section>
  </main>
}
