ALTER TABLE `SalonPost`
  ADD COLUMN `viewCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `watermarkEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `watermarkOpacity` INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN `watermarkPosition` ENUM('TOP', 'BOTTOM', 'LEFT', 'RIGHT', 'TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT') NOT NULL DEFAULT 'BOTTOM_RIGHT';

ALTER TABLE `SalonPostMedia`
  ADD COLUMN `originalObjectKey` VARCHAR(512) NULL,
  ADD COLUMN `originalFilename` VARCHAR(255) NULL,
  ADD COLUMN `originalMimeType` VARCHAR(100) NULL,
  ADD COLUMN `originalSize` INTEGER NULL;
